// ==UserScript==
// @name           RPG Maker MV part trans
// @namespace      http://userscripts.org/users/23652
// @description    Replaces Japanese text for RPG Maker MV json files
// @include        file://localhost/*/*.json
// @grant          none
// @copyright      JoeSimmons
// @version        1.1.0
// @project page   https://github.com/Anon7404/DLStrans/tree/MV-partial-translation
// @downloadURL    https://raw.github.com/Anon7404/DLStrans/MV-partial-translation/RPG_Maker_MV_part_trans.user.js
// @updateURL      https://raw.github.com/Anon7404/DLStrans/MV-partial-translation/RPG_Maker_MV_part_trans.user.js
// ==/UserScript==
(function () {
    'use strict';


    /*
        NOTE: 
            You can use \\* to match actual asterisks instead of using it as a wildcard!
            The examples below show a wildcard in use and a regular asterisk replacement.
    */

    var words = {
    ///////////////////////////////////////////////////////


        // Syntax: 'Search word' : 'Replace word',
// Automatic line separator, remove /* and */ for it to work
/*        '"\,"' : '",\n"',
        '}\,{' : '},\n{',
        '"]\,"' : '"],\n"',
        '\,"description"\:"' : '\,\n"description"\:"',
        '\,"name"\:"' : '\,\n"name"\:"',
        '\,"message1"\:"' : '\,\n"message1"\:"',
*/        //'' : '',
// Character names for Actors file
// maps partially contain matches with this too,
// so better to comment entries here before continuing with maps 
        '"リリス"' : '"Lilith"',
        //'"jp.name"' : '"tl.name"',
// Character names for Map files
        '<リリス>' : '<Lilith>',
        //'<jp.name>' : '<tl.name>',
// Translations for System file
// armorTypes
        '"一般防具"' : '"General Armor"',
        '"魔法防具"' : '"Magic Armor"',
        '"軽装防具"' : '"Light Armor"',
        '"重装防具"' : '"Heavy Armor"',
        '"小型盾"' : '"Small Shield"',
        '"大型盾"' : '"Large Shield"',
        '"アクセサリ"' : '"Accessory"',
        //'' : '',
// elements
        '"物理"' : '"Physical"',
        '"炎"' : '"Fire"',
        '"氷"' : '"Ice"',
        '"雷"' : '"Thunder"',
        '"水"' : '"Water"',
        '"土"' : '"Earth"',
        '"風"' : '"Wind"',
        '"光"' : '"Light"',
        '"闇"' : '"Darkness"',
        //'' : '',
// equipTypes
        '"武器"' : '"Weapon"',
        '"盾"' : '"Shield"',
        '"頭"' : '"Head"',
        '"身体"' : '"Body"',
        '"装飾品"' : '"Accessory"',
// gameTitle
        //'' : '',
// skillTypes
        '"魔法"' : '"Magic"',
        '"戦技"' : '"Skills"',
        '"パッシヴスキル"' : '"Passive skill"',
        '"バトルスキル"' : '"Battle skill"',
        '"マジックスキル"' : '"Magic skill"',
// terms : basic
        '"レベル"' : '"Level"',
        '"ＨＰ"' : '"HP"',
        '"ＭＰ"' : '"MP"',
        '"ＴＰ"' : '"TP"',
        '"経験値"' : '"Experience"',
// commands
        '"戦う"' : '"Fight"',
        '"逃げる"' : '"Escape"',
        '"攻撃"' : '"Attack"',
        '"防御"' : '"Guard"',
        '"アイテム"' : '"Item"',
        '"スキル"' : '"Skill"',
        '"装備"' : '"Equip"',
        '"ステータス"' : '"Status"',
        '"並び替え"' : '"Formation"',
        '"セーブ"' : '"Save"',
        '"ゲーム終了"' : '"Quit Game"',
        '"オプション"' : '"Option"',
        '"防具"' : '"Armor"',
        '"大事なもの"' : '"Key Items"',
        '"最強装備"' : '"Optimize"',
        '"全て外す"' : '"Clear"',
        '"ニューゲーム"' : '"New Game"',
        '"コンティニュー"' : '"Continue"',
        '"タイトルへ"' : '"Title"',
        '"やめる"' : '"Cancel"',
        '"購入する"' : '"Buy"',
        '"売却する"' : '"Sell"',
// params
        '"最大ＨＰ"' : '"Max HP"',
        '"最大ＭＰ"' : '"Max MP"',
        '"攻撃力"' : '"Attack"',
        '"防御力"' : '"Defense"',
        '"魔法力"' : '"Magic"',
        '"魔法防御"' : '"M.Defense"',
        '"敏捷性"' : '"Agility"',
        '"運"' : '"Luck"',
        '"命中率"' : '"Hit"',
        '"回避率"' : '"Evasion"',
        '"魔力"' : '"M.Attack"',
        '"すばやさ"' : '"Speed"',
// messages
// Volume Options
   // meVolume
        '"ME 音量"' : '"ME Volume"',
   // seVolume
        '"SE 音量"' : '"SE Volume"',
   // bgmVolume
        '"BGM 音量"' : '"BGM Volume"',
   // bgsVolume
        '"BGS 音量"' : '"BGS Volume"',
// Shop Screen
   // possession
        '"持っている数"' : '"Possession"',
// Status Screen
   // expTotal
        '"現在の%1"' : '"Current %1"',
   // expNext
        '"次の%1まで"' : '"To next %1"',
// Save/Load Screen
   // saveMessage
        '"どのファイルにセーブしますか？"' : '"Save to which file?"',
   // loadMessage
        '"どのファイルをロードしますか？"' : '"Load which file?"',
   // file
        '"ファイル"' : '"File"',
// Display when there are multiple members
   // partyName
        '"%1たち"' : '"%1\'s Party"',
// Basic Battle Messages
   // emerge
        '"%1が出現！"' : '"%1 emerged!"',
   // preemptive
        '"%1は先手を取った！"' : '"%1 got the upper hand!"',
   // surprise
        '"%1は不意をつかれた！"' : '"%1 was surprised!"',
   // escapeStart
        '"%1は逃げ出した！"' : '"%1 has started to escape!"',
   // escapeFailure
        '"しかし逃げることはできなかった！"' : '"However, it was unable to escape!"',
// Battle Ending Messages
   // victory
        '"%1の勝利！"' : '"%1 was victorious!"',
   // defeat
        '"%1は戦いに敗れた。"' : '"%1 was defeated."',
   // obtainExp
        '"%1 の%2を獲得！"' : '"%1 %2 were received!"',
   // obtainGold
        '"お金を %1\\\\G 手に入れた！"' : '"%1\\\\G were obtained!"',
   // obtainItem
        '"%1を手に入れた！"' : '"%1 was found!"',
   // levelUp
        '"%1は%2 %3 に上がった！"' : '"%1 is now %2 %3!"',
   // obtainSkill
        '"%1を覚えた！"' : '"%1 was learned!"',
// Item Use
   // useItem
        '"%1は%2を使った！"' : '"%1 uses %2!"',
// Critical Hit
   // criticalToActor
        '"痛恨の一撃！！"' : '"A painful blow!!"',
   // criticalToEnemy
        '"会心の一撃！！"' : '"An excellent hit!!"',
// Results for Actions on Actors
   // actorDamage
        '"%1は %2 のダメージを受けた！"' : '"%1 took %2 damage!"',
   // actorRecovery
        '"%1の%2が %3 回復した！"' : '"%1 recovered %2 %3"',
   // actorGain
        '"%1の%2が %3 増えた！"' : '"%1 gained %2 %3!"',
   // actorLoss
        '"%1の%2が %3 減った！"' : '"%1 lost %2 %3!"',
   // actorDrain
        '"%1は%2を %3 奪われた！"' : '"%1 was drained of %2 %3!"',
   // actorNoDamage
        '"%1はダメージを受けていない！"' : '"%1 took no damage!"',
   // actorNoHit
        '"ミス！　%1はダメージを受けていない！"' : '"Miss! %1 took no damage!"',
// Results for Actions on Enemy
   // enemyDamage
        '"%1に %2 のダメージを与えた！"' : '"%1 took %2 damage!"',
   // enemyDrain
        '"%1の%2を %3 奪った！"' : '"%1 was drained of %2 %3!"',
   // enemyNoDamage
        '"%1にダメージを与えられない！"' : '"%1 took no damage!"',
   // enemyNoHit
        '"ミス！　%1にダメージを与えられない！"' : '"Miss! %1 took no damage!"',
// Evasion/Reflection
   // evasion
        '"%1は攻撃をかわした！"' : '"%1 evaded the attack!"',
   // magicEvasion
        '"%1は魔法を打ち消した！"' : '"%1 nullified the magic!"',
   // magicReflection
        '"%1は魔法を跳ね返した！"' : '"%1 reflected the magic!"',
   // counterAttack
        '"%1の反撃！"' : '"%1 counterattacked!"',
   // substitute
        '"%1が%2をかばった！"' : '"%1 protected %2!"',
// Status Increase/Decrease
   // buffAdd
        '"%1の%2が上がった！"' : '"%1\'s %2 went up!"',
   // debuffAdd
        '"%1の%2が下がった！"' : '"%1\'s %2 went down!"',
   // buffRemove
        '"%1の%2が元に戻った！"' : '"%1\'s %2 returned to normal!"',
// Skill and Item Failure
   // actionFailure
        '"%1には効かなかった！"' : '"There was no effect on %1!"',
// Other
   // alwaysDash
        '"常時ダッシュ"' : '"Always Dash"',
   // commandRemember
        '"コマンド記憶"' : '"Command Remember"',
// variables
        //'' : '',
// weaponTypes
        '"短剣"' : '"Dagger"',
        '"剣"' : '"Sword"',
        '"フレイル"' : '"Flail"',
        '"斧"' : '"Axe"',
        '"ムチ"' : '"Whip"',
        '"杖"' : '"Cane"',
        '"弓"' : '"Bow"',
        '"クロスボウ"' : '"Crossbow"',
        '"銃"' : '"Gun"',
        '"爪"' : '"Claw"',
        '"グローブ"' : '"Glove"',
        '"槍"' : '"Spear"',
        //'' : '',
// Translations for Armors file
   //original
        '"------------鎧系"' : '"------------Armors"',
/*        '【一般装備】' : '[General Equipment] ',
        '【軽装備】' : '[Light Equipment] ',
        '【重装備】' : '[Heavy Equipment] ',
        '【魔法装備】' : '[Magic Equipment] ',
        '【小型盾】' : '[Small Shield] ',
        '【大型盾】' : '[Large Shield] ',
        '【装飾品】' : '[Accessory] ',
*/        '【一般装備】' : '',
        '【軽装備】' : '',
        '【重装備】' : '',
        '【魔法装備】' : '',
        '【小型盾】' : '',
        '【大型盾】' : '',
        '【装飾品】' : '',
        '通気性の高い布の服。"' : 'Linen clothing with high \\nbreathability."',
        '布の服"' : 'Linen Clothing"',
        'なめし皮で作られたベスト。"' : 'A vest made of tanned hide."',
        'レザーベスト"' : 'Leather Vest"',
        '過酷な旅にも耐えられる丈夫な服。"' : 'Durable clothing that can \\nwithstand rough travels."',
        '冒険者の服"' : 'Adventurer\'s Clothing"',
        'にかわで固めた硬皮のベスト。"' : 'A vest made of leather \\nhardened with glue."',
        'ハードレザー"' : 'Hard Leather"',
        '鋼板で補強したなめし皮製の服。"' : 'Tanned hide clothing reinforced \\nwith steel plates."',
        'ブリガンダイン"' : 'Brigandine"',
        '丈夫な布で作られた鎧。"' : 'Armor made of tough cloth."',
        'クロースアーマー"' : 'Cloth Armor"',
        'なめし皮を重ねて組んだ鎧。"' : 'Armor made of layered hide."',
        'レザーアーマー"' : 'Leather Armor"',
        '青銅製の胸当て。"' : 'A breastplate made of bronze."',
        'ブロンズブレスト"' : 'Bronze Breastplate"',
        '鋼鉄製の胸当て。"' : 'A breastplate made of iron steel."',
        'アイアンブレスト"' : 'Iron Breastplate"',
        'ミスリルで作られた胸当て。"' : 'A breastplate made of mithril."',
        'ミスリルブレスト"' : 'Mithril Breastplate"',
        'ドラゴンの鱗作られた胸当て。"' : 'A breastplate made of dragon scales."',
        'ドラゴンブレスト"' : 'Dragon Breastplate"',
        '青銅製の鎧。"' : 'Armor made of bronze."',
        'ブロンズアーマー"' : 'Bronze Armor"',
        '鋼鉄製の鎧。"' : 'Armor made of iron steel."',
        'アイアンアーマー"' : 'Iron Armor"',
        'ミスリルで作られた鎧。"' : 'Armor made of mithril."',
        'ミスリルアーマー"' : 'Mithril Armor"',
        'ドラゴンの鱗で作られた鎧。"' : 'Armor made of dragon scales."',
        'ドラゴンアーマー"' : 'Dragon Armor"',
        '広く普及している一般的なローブ。"' : 'A basic, widely prevalent robe."',
        '木綿のローブ"' : 'Cotton Robe"',
        '絹で作られた上質なマント。"' : 'A high-quality cloak made of silk."',
        '絹のマント"' : 'Silk Cloak"',
        'ルーン文字が刻まれたローブ。"' : 'A robe inscribed with runic letters."',
        '術士のローブ"' : 'Tactician\'s Robe"',
        '魔力が織り込まれたローブ。"' : 'A robe interwoven with magical \\npowers."',
        '賢者のローブ"' : 'Sage\'s Robe"',
        '精霊王の力が宿る究極のマント。"' : 'A cloak that houses the power of \\nspirits."',
        'エレメンタルマント"' : 'Elemental Cloak"',
        '------------盾系"' : '------------Shields"',
        '攻撃を受け流すための小型盾。"' : 'A small shield for deflecting attacks."',
        'バックラー"' : 'Buckler"',
        '鉄の枠で補強した木製の円盾。"' : 'A round, wooden shield reinforced \\nwith an iron frame. "',
        'ラウンドバックラー"' : 'Round Buckler"',
        '表面に攻撃用のトゲがついた円盾。"' : 'A round shield with attack spikes \\nattached."',
        'スパイクバックラー"' : 'Spiked Buckler"',
        'ミスリルで作られた小型盾。"' : 'A small shield made of mithril."',
        'ミスリルバックラー"' : 'Mithril Buckler"',
        '竜の鱗から作られた小型盾。"' : 'A small shield made of dragon scales."',
        'ドラゴンバックラー"' : 'Dragon Buckler"',
        'ごく普通の木製の大きな盾。"' : 'A large, average wooden shield."',
        'ウッドシールド"' : 'Wooden Shield"',
        '青銅の板で作られた大きな盾。"' : 'A large shield made of bronze plates."',
        'ブロンズシールド"' : 'Bronze Shield"',
        '鋼鉄製の大きな盾。"' : 'A large shield made of iron steel."',
        'アイアンシールド"' : 'Iron Shield"',
        'ミスリルで作られた大型の盾"' : 'A large shield made of mithril."',
        'ミスリルシールド"' : 'Mithril Shield"',
        '竜の鱗から作られた大型の盾。"' : 'A large shield made of dragon scales."',
        'ドラゴンシールド"' : 'Dragon Shield"',
        '守護の魔法がかけられた腕輪。"' : 'A bangle enchanted with protective \\nmagic."',
        'ウッドバングル"' : 'Wooden Bangle"',
        'ブロンズバングル"' : 'Bronze Bangle"',
        'アイアンバングル"' : 'Iron Bangle"',
        'ミスリルバングル"' : 'Mithril Bangle"',
        'ドラゴンバングル"' : 'Dragon Bangle"',
        '------------兜系"' : '------------Helmets"',
        '額を守る布製のハチマキ。"' : 'A cloth headband for protecting \\nthe forehead."',
        'バンダナ"' : 'Bandana"',
        '額を守る皮製のハチマキ。"' : 'A leather headband for protecting \\nthe forehead."',
        'レザーバンダナ"' : 'Leather Bandana"',
        '皮で作られた帽子。"' : 'A hat made of leather."',
        '皮の帽子"' : 'Leather Hat"',
        '重ねて巻きつけて頭を守る厚手の布。"' : 'A thick cloth layered and wrapped \\naround the head for protection."',
        'ターバン"' : 'Turban"',
        '鳥の羽がついたオシャレな帽子。"' : 'A fancy hat with bird feathers \\nattached."',
        '羽根付き帽子"' : 'Feathered Hat"',
        'なめし皮で作られた帽子。"' : 'A hat made of tanned hide."',
        'レザーキャップ"' : 'Leather Cap"',
        '木で作られた軽量のヘルメット。"' : 'A light helmet made of wood."',
        'ウッドキャップ"' : 'Wooden Cap"',
        '銅板で強化された軽量のヘルメット。"' : 'A light helmet reinforced with \\nbronze plates."',
        'ブロンズキャップ"' : 'Bronze Cap"',
        '鉄板で強化された軽量のヘルメット。"' : 'A light helmet reinforced with \\niron plates."',
        'アイアンキャップ"' : 'Iron Cap"',
        'ミスリルで強化された軽量のヘルメット。"' : 'A light helmet reinforced with \\nmithril."',
        'ミスリルキャップ"' : 'Mithril Cap"',
        'ドラゴンの鱗で強化された軽量のヘルメット。"' : 'A light helmet reinforced with \\ndragon scales."',
        'ドラゴンキャップ"' : 'Dragon Cap"',
        '細かい鎖を編んで作られた頭巾。"' : 'A hood made with fine, woven chains."',
        'チェインコイフ"' : 'Chainmail Coif"',
        '厚い青銅の板で作られた兜。"' : 'A helmet made with thick bronze \\nplates."',
        'ブロンズヘルム"' : 'Bronze Helm"',
        '厚い鋼鉄の板で作られた兜。"' : 'A helmet made with thick iron\\nplates."',
        'アイアンヘルム"' : 'Iron Helm"',
        'ミスリルで作られた兜。"' : 'A helmet made of mithril."',
        'ミスリルヘルム"' : 'Mithril Helm"',
        'ドラゴンの鱗で作られた兜。"' : 'A helmet made with dragon scales."',
        'ドラゴンヘルム"' : 'Dragon Helm"',
        'なめし皮で作られたつばの広い三角の帽子。"' : 'A triangular, tanned hide hat with \\na wide brim."',
        'とんがり帽子"' : 'Pointed Hat"',
        '守護の魔法がかけられた簡素な冠。"' : 'A simple crown enchanted with \\nprotective magic."',
        'サークレット"' : 'Circlet"',
        '守護の魔法がかけられた銀細工の冠。"' : 'A silver crown enchanted with \\nprotective magic."',
        'シルバーサークレット"' : 'Silver Circlet"',
        '守護の魔法がかけられた純金の冠。"' : 'A pure gold crown enchanted with \\nprotective magic."',
        'ゴールドサークレット"' : 'Gold Circlet"',
        '守護の魔法がかけられたミスリルの冠。"' : 'A mithril crown enchanted with \\nprotective magic."',
        'ミスリルサークレット"' : 'Mithril Circlet"',
        '守護の魔法がかけられた賢者の冠。"' : 'A sage\'s crown enchanted with \\nprotective magic."',
        'マスターサークレット"' : 'Master Circlet"',
        '------------装飾品系"' : '------------Accessories"',
        '防御力を高めてくれるお守り。"' : 'A charm that increases defense."',
        'ガードストーン"' : 'Guard Stone"',
        '防御力を高めてくれる指輪。"' : 'A ring that increases defense."',
        'ガードリング"' : 'Guard Ring"',
        '攻撃力を高めてくれるお守り。"' : 'A charm that increases attack."',
        'パワーストーン"' : 'Power Stone"',
        '攻撃力を高めてくれる指輪。"' : 'A ring that increases attack."',
        'パワーリング"' : 'Power Ring"',
        '敏捷性を高めてくれるお守り。"' : 'A charm that increases agility."',
        'スピードストーン"' : 'Speed Stone"',
        '敏捷性を高めてくれる指輪。"' : 'A ring that increases agility."',
        'スピードリング"' : 'Speed Ring"',
        '運を高めてくれるお守り。"' : 'A charm that increases luck."',
        'ラッキーストーン"' : 'Lucky Stone"',
        '運を高めてくれる指輪。"' : 'A ring that increases luck."',
        'ラッキーリング"' : 'Lucky Ring"',
        '魔法力を高めてくれるお守り。"' : 'A charm that increases M.Attack."',
        'マジカルストーン"' : 'Magical Stone"',
        '魔法力を高めてくれる指輪。"' : 'A ring that increases M.Attack."',
        'マジカルリング"' : 'Magical Ring"',
        'シューターストーン"' : 'Shooter Stone"',
        '攻撃の命中率を高めてくれるお守り。"' : 'Increases the hit rate of attacks."',
        'シューターリング"' : 'Shooter Ring"',
        '魔力の消費を20％抑えてくれるお守り。"' : 'A charm that reduces magic cost by 20%."',
        'マスターストーン"' : 'Master Stone"',
        '魔力の消費を50％抑えてくれる指輪。"' : 'A ring that reduces magic cost by 50%."',
        'マスターリング"' : 'Master Ring"',
        '毒・麻痺に、かかりにくくなる指輪。"' : 'A ring that helps prevent poisoned and \\nparalyzed states."',
        'ポイズンガード"' : 'Poison Guard"',
        '毒・麻痺を完全に防ぐ指輪。"' : 'A ring that entirely prevents poisoned \\nand paralyzed states."',
        'ポイズンガードＳ"' : 'Super Poison Guard"',
        '睡眠・沈黙・混乱・魅了・激昂に\\nかかりにくくなる指輪。"' : 'A ring that helps prevent sleep, \\nsilence, confusion, fascination, and rage states."',
        'メンタルガード"' : 'Mental Guard"',
        '睡眠・沈黙・混乱・魅了・激昂を\\n完全に防ぐ指輪。"' : 'A ring that entirely prevents sleep, \\nsilence, confusion, fascination, and rage states."',
        'メンタルガードＳ"' : 'Super Mental Guard"',
        '先制攻撃を行える確率を上げます。"' : 'Raises the chance of performing a \\npreemptive attack."',
        'エネミーレーダー"' : 'Enemy Radar"',
        '不意打ち攻撃を受けなくなります。"' : 'Prevents surprise attacks."',
        'ワーニングベル"' : 'Warning Bell"',
        'ＴＰを次の戦闘に持ち越せるようになります。"' : 'Allows you to carryover TP over into the \\nnext battle."',
        'ＴＰストッカー"' : 'Stocker"',
        'ＴＰのチャージ率が上昇します。"' : 'Increases TP charge rate."',
        'ガッツリング"' : 'Ring of Guts"',
        'ＭＰの消費率を下げます。"' : 'Decreases MP cost rate."',
        'ＭＰキーパー"' : 'MP Keeper"',
        '四大精霊の加護のもと\\n火、水、風、土属性攻撃で受けるダメージを半減する。"' : 'Damage inflicted by water, fire, wind, \\nand earth attacks is halved."',
        'エレメンタルガード"' : 'Elemental Guard"',
        //'' : '"Sharpens eyesight and increases hit rate."',
        //'' : '"Spectacles"',
        //'' : '',
// Translations for Classes file
   //original
        '"name"\:"剣士"' : '"name"\:"Swordsman"',
        '"name"\:"魔法使い"' : '"name"\:"Sorcerer"',
        '"name"\:"魔術師"' : '"name"\:"Mage"',
        '"name"\:"僧侶"' : '"name"\:"Priest"',
        '"name"\:"騎士"' : '"name"\:"Knight"',
        '"name"\:"格闘家"' : '"name"\:"Martial Artist"',
        '"name"\:"魔法剣士"' : '"name"\:"Magic Swordsman"',
        '"name"\:"狩人"' : '"name"\:"Hunter"',
        '"name"\:"盗賊"' : '"name"\:"Bandit"',
        //'' : '',
// Translations for Enemies file
   //original
        '"スライム"' : '"Slime"',
        '"ホーネット"' : '"Hornet"',
        '"デビルプラント"' : '"Demon Plant"',
        '"キラーラット"' : '"Killer Rat"',
        '"スパイダー"' : '"Spider"',
        '"バット"' : '"Bat"',
        '"スネイク"' : '"Snake"',
        '"インプ"' : '"Imp"',
        '"ミミック"' : '"Mimic"',
        '"オーク"' : '"Orc"',
        //'' : '',
// Translations for Items file
   //original
        '"回復アイテムより上位に表示したいアイテム用の枠です。"' : '"Below are spaces for when you would like to display \\nitems above the recovery items."',
        '"-----予備"' : '"-----Spare"',
        '"-----回復系"' : '"-----Recovery Items"',
        '"ＨＰを５００ポイント回復する。"' : '"Recovers HP by 500 points."',
        '"ポーション"' : '"Potion"',
        '"ＨＰを1５００ポイント回復する。"' : '"Recovers HP by 1500 points."',
        '"ハイポーション"' : '"Super Potion"',
        '"ＨＰを完全に回復する。"' : '"Completely recovers HP."',
        '"フルポーション"' : '"Full Potion"',
        '"ＭＰを３００ポイント回復する。"' : '"Recovers MP by 300 points."',
        '"マジックウォーター"' : '"Magic Water"',
        '"戦闘不能から復活させる。（ＨＰ半分回復）"' : '"Raises the user from the dead. (Recovers HP by half.)"',
        '"スティミュラント"' : '"Stimulant"',
        '"戦闘不能以外の状態異常を回復する。"' : '"Heals the user of status ailments besides dead."',
        '"ディスペルハーブ"' : '"Dispel Herb"',
        '"ステートが増えたら追加する事。"' : '"Add when states increase."',
        '"毒、麻痺、しびれ状態を治療する。"' : '"Cures poisoned"',
        '"アンチドーテ"' : '"Antidote"',
        '"ＨＰとＭＰを半分回復する。"' : '"Recovers HP and MP by half"',
        '"ミラクルドロップ"' : '"Miracle Drop"',
        '"ＨＰとＭＰを完全に回復する。"' : '"Completely recovers HP and MP."',
        '"エリクサー"' : '"Elixir"',
   //other
        '"マナポーション"' : '"Mana Potion"',
        '"ハイマナポーション"' : '"Hi-Mana Potion"',
        '"エクスポーション"' : '"X-Potion"',
        '"エクスマナポーション"' : '"X-Mana Potion"',
        '"瞬間裁縫セット"' : '"Sewing Kit"',
        '"破れた衣服をすぐに元通りにできる"' : '"Repairs Torn Clothes."',
        '"完全回復薬　HPとMPともに全回復"' : '"Complete Recovery Item\/Always Useable Can be used in combat, Fully recovers HP."',
        //'' : '',
// Translations for Skills file
   //original
        '"の攻撃！"' : '" attacks!"',
        '"以下は、メニューを開いたとき、戦闘用のスキルより\\n上部に表示したいスキル用の枠です。"' : '"Below are spaces for when you would like to display \\nthings above skills when you open the menu."',
        '"-----　予備"' : '"-----　Spare"',
        '"以下は、主に敵が使用する前提のスキルです。\\n消費ＴＰが設定されていません。"' : '"Below are skills mainly for enemies to use. \\nTP cost is not set."',
        '"-----　エネミー"' : '"-----　Enemy"',
        '"敵単体に対して連続して攻撃を行う。"' : '"Performs a series of attacks on an enemy."',
        '"連続攻撃"' : '"Dual Attack"',
        '"ランダムな敵単体に対して２回攻撃を行う。"' : '"Performs a double attack on a random enemy."',
        '"２回攻撃"' : '"Double Attack"',
        '"ランダムな敵単体に対して３回攻撃を行う。"' : '"Performs a triple attack on a random enemy."',
        '"３回攻撃"' : '"Triple Attack"',
        '"使用者が戦闘から離脱します。"' : '"The user flees from battle."',
        '"は逃げてしまった。"' : '" flees."',
        '"ただ見てるだけ。"' : '"Just watching."',
        '"は様子を見ている。"' : '" waits."',
        '"様子を見る"' : '"Wait"',
        '"敵単体のＨＰを吸収する。"' : '"Absorbs HP from an enemy."',
        '"の吸血攻撃！"' : '" sucks blood!"',
        '"吸血"' : '"Blood Suck"',
        '"使用者のＨＰを回復する。"' : '"Recovers the user\'s HP."',
        '"は%1した！"' : '" %1s!"',
        '"瞑想"' : '"Meditate"',
        '"敵単体に毒針を刺し、麻痺状態にする。"' : '"Stabs an enemy with poison needles, paralyzing them."',
        '"痺れ針"' : '"Tranquilizer"',
        '"敵単体にダメージを与え、バランスを崩させる。"' : '"Inflicts damage and causes an enemy to lose balance."',
        '"は体当たりをした！"' : '" does bodyslam!"',
        '"体当たり"' : '"Bodyslam"',
        '"敵単体に雷属性のダメージを与え、麻痺させる。"' : '"Inflicts thunder-type damage and paralyzes an enemy."',
        '"電撃"' : '"Shock"',
        '"敵単体に粘液を付着させ、敏捷性を下げる。"' : '"Covers an enemy in slime and lowers their agility."',
        '"は粘液を吹きかけた！"' : '" shoots out slime!"',
        '"粘液"' : '"Slime"',
        '"敵単体に毒液を噴きかけ、毒状態にする。"' : '"Sprays an enemy with venom and poisons them."',
        '"は%1を放った！"' : '" uses %1!"',
        '"毒液"' : '"Venom"',
        '"使用者の闘志を奮い立たたせ、能力を強化する。"' : '"Rouses the user\'s fighting spirit and fortifies \\ntheir abilities."',
        '"は、闘志をみなぎらせた！"' : '" rouses their fighting spirit!"',
        '"咆哮"' : '"Shout"',
        '"敵単体のＭＰを吸収する。"' : '"Absorbs MP from an enemy."',
        '"は奇妙なダンスを踊った！"' : '" dances bizarrely!"',
        '"奇妙なダンス"' : '"Bizarre Dance"',
        '"敵単体を睨みつけ、麻痺させる。"' : '"Glares at an enemy and paralyzes them."',
        '"麻痺睨み"' : '"Petrify"',
        '"敵単体を暗闇状態にする。"' : '"Blinds an enemy."',
        '"目潰し"' : '"Eye Poke"',
        '"敵全体を暗闇状態にする。"' : '"Blinds all enemies."',
        '"砂けむり"' : '"Sandstorm"',
        '"閃光"' : '"Flash"',
        '"敵全体を毒状態にする。"' : '"Poisons all enemies."',
        '"猛毒の霧"' : '"Toxic Fog"',
        '"敵全体を睡眠状態にする。"' : '"Puts all enemies to sleep."',
        '"は%1を歌った！"' : '" sings a %1!"',
        '"子守唄"' : '"Lullaby"',
        '"敵全体を魅了する。"' : '"Fascinates all enemies."',
        '"誘惑の歌"' : '"Alluring Melody"',
        '"敵全体の魔法を封印する。"' : '"Seals all enemies\' magic."',
        '"沈黙の歌"' : '"Song of Silence"',
        '"敵全体を混乱状態にする。"' : '"Confuses all enemies."',
        '"超音波"' : '"Sonic Wave"',
        '"敵全体に大地属性のダメージを与える。"' : '"Inflicts ground-type damage on all enemies."',
        '"石つぶて"' : '"Throwing Stone"',
        '"敵全体に風属性のダメージを与える。"' : '"Inflicts wind-type damage on all enemies."',
        '"鎌いたち"' : '"Kamaitachi"',
        '"敵全体に炎属性のダメージを与える。"' : '"Inflicts fire-type damage on all enemies."',
        '"ファイアブレス"' : '"Fire Breath"',
        '"敵全体に氷属性のダメージを与える。"' : '"Inflicts ice-type damage on all enemies."',
        '"アイスブレス"' : '"Ice Breath"',
        '"敵全体に土属性のダメージを与える。"' : '"Inflicts earth-type damage on all enemies."',
        '"は%1をおこした！"' : '" causes an %1!"',
        '"地震"' : '"Earthquake"',
        '"敵全体に水属性のダメージを与える。"' : '"Inflicts water-type damage on all enemies."',
        '"津波"' : '"Tsunami"',
        '"ひっかく"' : '"Scratch"',
        '"以下は、主にプレイヤーが使用する前提の魔法スキルです。\\n敵が使用してもいいです。"' : '"Below are magic skills mainly for the player to use, \\nbut enemies may also use them."',
        '"-----　基本の魔法"' : '"-----　Basic Magic"',
        '"は%1を唱えた！"' : '" casts %1!"',
        '"味方単体のＨＰを回復する。"' : '"Recovers an ally\'s HP."',
        '"ヒールⅠ"' : '"Heal I"',
        '"ヒールⅡ"' : '"Heal II"',
        '"ヒールⅢ"' : '"Heal III"',
        '"味方全体のＨＰを回復する。"' : '"Recovers all allies\' HP."',
        '"リカバーⅠ"' : '"Recover I"',
        '"リカバーⅡ"' : '"Recover II"',
        '"リカバーⅢ"' : '"Recover III"',
        '"味方単体の毒・麻痺・睡眠を治療する。"' : '"Cures an ally\'s poisoned"',
        '"キュアーⅠ"' : '"Cure I"',
        '"味方単体の戦闘不能以外の状態異常を治療する。"' : '"Cures an ally\'s status ailments other than dead."',
        '"キュアーⅡ"' : '"Cure II"',
        '"味方全体の戦闘不能以外の状態異常を治療する。"' : '"Cures all allies\' status ailments other than dead."',
        '"キュアーⅢ"' : '"Cure III"',
        '"味方単体を戦闘不能から復活させる。"' : '"Raises an ally from the dead."',
        '"レイズⅠ"' : '"Raise I"',
        '"味方単体を戦闘不能から復活させ、ＨＰを大きく回復する。"' : '"Raises an ally from the dead and greatly recovers \\ntheir HP."',
        '"レイズⅡ"' : '"Raise II"',
        '"ポイズン"' : '"Poison"',
        '"ブラインド"' : '"Blind"',
        '"コンフューズ"' : '"Confuse"',
        '"サイレンス"' : '"Silence"',
        '"スリープ"' : '"Sleep"',
        '"敵全体を麻痺状態にする。"' : '"Paralyzes all enemies."',
        '"パラライズ"' : '"Paralyze"',
        '"味方単体の攻撃力を上げる。\\n２回まで重ねがけできる。"' : '"Increases an ally\'s attack. \\nUsable up to 2 times in a row."',
        '"ウェポンブレス"' : '"Weapon Breath"',
        '"敵全体の攻撃力を下げる。\\n２回まで重ねがけできる。"' : '"Decreases all enemies\' attacks. \\nUsable up to 2 times in a row."',
        '"ウェポンカース"' : '"Weapon Curse"',
        '"味方単体の防御力を上げる。\\n２回まで重ねがけできる。"' : '"Increases an ally\'s defense. \\nUsable up to 2 times in a row."',
        '"アーマーブレス"' : '"Armor Breath"',
        '"敵全体の防御力を下げる。\\n２回まで重ねがけできる。"' : '"Decreases all enemies\' defense. \\nUsable up to 2 times in a row."',
        '"アーマーカース"' : '"Armor Curse"',
        '"味方単体の魔法力を上げる。\\n２回まで重ねがけできる。"' : '"Increases an ally\'s M.Attack. \\nUsable up to 2 times in a row."',
        '"スピリットブレス"' : '"Spirit Breath"',
        '"敵全体の魔法力を下げる。\\n２回まで重ねがけできる。"' : '"Decreases all enemies\' M.Attack. \\nUsable up to 2 times in a row."',
        '"スピリットカース"' : '"Spirit Curse"',
        '"味方単体の魔法防御力を上げる。\\n２回まで重ねがけできる。"' : '"Increases an ally\'s M.Defense. \\nUsable up to 2 times in a row."',
        '"ディバインブレス"' : '"Divine Breath"',
        '"敵全体の魔法防御力を下げる。\\n２回まで重ねがけできる。"' : '"Decreases all enemies\' M.Defense. \\nUsable up to 2 times in a row."',
        '"ディバインカース"' : '"Divine Curse"',
        '"味方単体の敏捷を上げる。\\n２回まで重ねがけできる。"' : '"Increases an ally\'s agility. \\nUsable up to 2 times in a row."',
        '"クイックムーブ"' : '"Quicken Movement"',
        '"敵全体の敏捷を下げる。\\n２回まで重ねがけできる。"' : '"Decreases all enemies\' agility. \\nUsable up to 2 times in a row."',
        '"スロームーブ"' : '"Slow Movement"',
        '"ライフドレイン"' : '"Life Drain"',
        '"マナドレイン"' : '"Mana Drain"',
        '"敵単体に炎属性のダメージを与える。"' : '"Inflicts fire-type damage on an enemy."',
        '"ファイアⅠ"' : '"Fire I"',
        '"ファイアⅡ"' : '"Fire II"',
        '"ファイアⅢ"' : '"Fire III"',
        '"フレイムⅠ"' : '"Flame I"',
        '"フレイムⅡ"' : '"Flame II"',
        '"フレイムⅢ"' : '"Flame III"',
        '"敵単体に氷属性のダメージを与える。"' : '"Inflicts ice-type damage on an enemy."',
        '"アイスⅠ"' : '"Ice I"',
        '"アイスⅡ"' : '"Ice II"',
        '"アイスⅢ"' : '"Ice III"',
        '"ブリザードⅠ"' : '"Blizzard I"',
        '"ブリザードⅡ"' : '"Blizzard II"',
        '"ブリザードⅢ"' : '"Blizzard III"',
        '"敵単体に雷属性のダメージを与える。"' : '"Inflicts thunder-type damage on an enemy."',
        '"サンダーⅠ"' : '"Thunder I"',
        '"サンダーⅡ"' : '"Thunder II"',
        '"サンダーⅢ"' : '"Thunder III"',
        '"敵全体に雷属性のダメージを与える。"' : '"Inflicts thunder-type damage on all enemies."',
        '"スパークⅠ"' : '"Spark I"',
        '"スパークⅡ"' : '"Spark II"',
        '"スパークⅢ"' : '"Spark III"',
        '"敵単体に水属性のダメージを与える。"' : '"Inflicts water-type damage on an enemy."',
        '"ウォーターⅠ"' : '"Water I"',
        '"ウォーターⅡ"' : '"Water II"',
        '"ウェーブⅠ"' : '"Wave I"',
        '"ウェーブⅡ"' : '"Wave II"',
        '"敵単体に大地属性のダメージを与える。"' : '"Inflicts ground-type damage on an enemy."',
        '"ストーンⅠ"' : '"Stone I"',
        '"ストーンⅡ"' : '"Stone II"',
        '"クェイクⅠ"' : '"Quake I"',
        '"クェイクⅡ"' : '"Quake II"',
        '"敵単体に風属性のダメージを与える。"' : '"Inflicts wind-type damage on an enemy."',
        '"ウインドⅠ"' : '"Wind I"',
        '"ウインドⅡ"' : '"Wind II"',
        '"トルネードⅠ"' : '"Tornado I"',
        '"トルネードⅡ"' : '"Tornado II"',
        '"敵単体に神聖属性のダメージを与える。"' : '"Inflicts divine-type damage on an enemy."',
        '"セイントⅠ"' : '"Saint I"',
        '"セイントⅡ"' : '"Saint II"',
        '"敵全体に神聖属性のダメージを与える。"' : '"Inflicts divine-type damage on all enemies."',
        '"スターライトⅠ"' : '"Starlight I"',
        '"スターライトⅡ"' : '"Starlight II"',
        '"敵単体に暗黒属性のダメージを与える。"' : '"Inflicts dark-type damage on an enemy."',
        '"シェイドⅠ"' : '"Shade I"',
        '"シェイドⅡ"' : '"Shade II"',
        '"敵全体に暗黒属性のダメージを与える。"' : '"Inflicts dark-type damage on all enemies."',
        '"ダークネスⅠ"' : '"Darkness I"',
        '"ダークネスⅡ"' : '"Darkness II"',
        '"敵単体に防御無視のダメージを与える。"' : '"Inflicts damage on an enemy regardless of defense."',
        '"バーストⅠ"' : '"Burst I"',
        '"バーストⅡ"' : '"Burst II"',
        '"敵全体に防御無視のダメージを与える。"' : '"Inflicts damage on all enemies regardless of defense."',
        '"ニュークリアⅠ"' : '"Nuke I"',
        '"ニュークリアⅡ"' : '"Nuke II"',
        '"以下は、主に剣士が使用する前提のスキルです。"' : '"Below are skills mainly for swordsmen to use."',
        '"-----　剣士・戦士系スキル"' : '"-----　Swordsman & Warrior Skills"',
        '"敵単体に対して強力な攻撃を行う。"' : '"Performs a powerful attack on an enemy."',
        '"強撃"' : '"Strong Attack"',
        '"敵全体に対して攻撃を行う。"' : '"Attacks all enemies."',
        '"は薙ぎ払った！"' : '" mows down the enemy!"',
        '"薙ぎ払い"' : '"Slash"',
        '"敵単体に対して２回攻撃を行う。"' : '"Performs an attack on an enemy twice."',
        '"の連続攻撃！"' : '" dual attacks!"',
        '"使用者の闘志を奮い立たたせ、攻撃力を上げる。\\n２回まで重ねがけできる。"' : '"Rouses the user\'s fighting spirit and increases \\nattack. Usable up to 2 times in a row."',
        '"は%1を入れた！"' : '" uses %1!"',
        '"気合い"' : '"Willpower"',
        '"は%1を行った！"' : '" performs %1!"',
        '"応急処置"' : '"First Aid"',
        '"敵単体に対して超強力な攻撃を行う。"' : '"Performs a super powerful attack on an enemy."',
        '"乙女の構え"' : '"Maiden\'s Stance"',
        '"敵全体に対して強攻撃を行う。"' : '"Performs a powerful attack on all enemies."',
        '"スピンクラッシュ"' : '"Spin Crash"',
        '"以下は、主に魔法使いが使用する前提のスキルです。"' : '"Below are skills mainly for sorcerers to use."',
        '"-----　僧侶・魔法使い系スキル"' : '"-----　Priest & Sorcerer Skills"',
        '"味方全体の防御力・魔法防御力を上げる。\\n２回まで重ねがけできる。"' : '"Increases all allies\' defense and M.Defense. \\nUsable up to 2 times in a row."',
        '"は祈りを捧げた！"' : '" offered prayer!"',
        '"マジックバリア"' : '"Magic Barrier"',
        '"５ターンの間、使用者の魔法力を大幅に上げる。"' : '"Greatly increases the user\'s M.Attack for 5 turns."',
        '"スペルエンハンス"' : '"Spell Enhancement"',
        '"味方全体の闘志を奮い立たたせ、攻撃力を上げる。\\n２回まで重ねがけできる。"' : '"Rouses all allies\' fighting spirit and increases \\nattack. Usable up to 2 times in a row."',
        '"は応援した！"' : '" gave encouragement!"',
        '"エール"' : '"Yell"',
        '"メテオ"' : '"Meteor"',
        '"５ターンの間、炎属性を付与する。"' : '"Bestows fire attributes for 5 turns."',
        '"ファイアウエポン"' : '"Fire Weapon"',
        '"５ターンの間、氷属性を付与する。"' : '"Bestows ice attributes for 5 turns."',
        '"アイスウエポン"' : '"Ice Weapon"',
        '"５ターンの間、雷属性を付与する。"' : '"Bestows thunder attributes for 5 turns."',
        '"サンダーウエポン"' : '"Thunder Weapon"',
        '"５ターンの間、使用者に向けられた攻撃魔法を反射する。"' : '"Reflects magic attacks aimed at the user for 5 turns."',
        '"マジックミラー"' : '"Magic Mirror"',
        '"以下は、主に騎士が使用する前提のスキルです。\\n（武器は、槍がメイン）"' : '"Below are skills mainly for knights to use. \\n(Weapons are mostly spears.)"',
        '"-----　騎士系スキル"' : '"-----　Knight Skills"',
        '"１ターンの間、ＨＰの少ない味方を自動的にかばう。"' : '"Automatically protects allies with low HP for 1 turn."',
        '"は仲間をかばっている。"' : '" protects team."',
        '"かばう"' : '"Protect"',
        '"誰よりも早く敵単体に攻撃を行なう。"' : '"Performs an attack on an enemy faster than anyone \\nelse."',
        '"隼突き"' : '"Falcon Thrust"',
        '"二段突き"' : '"Double Thrust"',
        '"敵単体に防御力無視の攻撃を行なう。"' : '"Inflicts damage on all enemies regardless of defense."',
        '"鎧通し"' : '"Armor Piercer"',
        '"は一喝した！"' : '" made a battle cry!"',
        '"一喝"' : '"Battle Cry"',
        '"風車"' : '"Windmill"',
        '"使用者のＴＰを少し増やす。"' : '"Slightly increases the user\'s TP."',
        '"は心を無にした！"' : '" cleared their mind!"',
        '"心頭滅却"' : '"Clear Mind"',
        '"敵４体に対してランダムに４回攻撃を行う。"' : '"Randomly performs 4 attacks on 4 enemies."',
        '"乱れ突き"' : '"Wild Thrust"',
        '"以下は、主に盗賊が使用する前提のスキルです。"' : '"Below are skills mainly for bandits to use."',
        '"-----　盗賊系スキル"' : '"-----　Bandit Skills"',
        '"使用者の敏捷を上げる。\\n"' : '"Increases the user\'s agility.\\n"',
        '"は%1を始めた！"' : '" started %1!"',
        '"準備運動"' : '"Warm-up"',
        '"閃光弾"' : '"Flare"',
        '"アイテムのドロップ率を上げる。"' : '"Increases items and money gained from battle for \\na while."',
        '"は隙をうかがっている。"' : '" observes the surroundings carefully."',
        '"隙をうかがう"' : '"Watchful Eye"',
        '"敵全体にダメージを与える。"' : '"Inflicts huge damage on all enemies."',
//        '"鎌いたち"' : '"Poised Sword"',
        '"標的になりにくくする。"' : '"Makes the user harder to target."',
//        '"は逃げてしまった。"' : '" hid."',
        '"隠れる"' : '"Hide"',
        '"以下は、主に格闘家が使用する前提のスキルです。"' : '"Below are skills mainly for martial artists to use."',
        '"-----　格闘家系スキル"' : '"-----　Martial Artist Skills"',
        '"敵全体にダメージを与え、バランスを崩させる。"' : '"Inflicts damage and causes all enemies to lose balance."',
        '"足払い"' : '"Sweep"',
        '"使用者の弱体化を治療する。"' : '"Cures the user from being weakened."',
        '"は%1を使った！"' : '" uses %1!"',
        '"気孔術"' : '"Qigong "',
        '"敵全体に強力なダメージを与える。"' : '"Inflicts huge damage on all enemies."',
        '"回し蹴り"' : '"Roundhouse Kick"',
        '"敵単体に防御無視の強力なダメージを与える。"' : '"Inflicts damage on an enemy regardless of defense."',
        '"猛虎乱舞"' : '"Tiger Dance"',
        '"以下は、主に狩人が使用する前提のスキルです。"' : '"Below are skills mainly for hunters to use."',
        '"-----　狩人系スキル"' : '"-----　Hunter Skills"',
        '"敵単体の攻撃力と防御力を下げる。"' : '"Decreases an enemy\'s attack and defense."',
        '"ポイントショット"' : '"Point Shot"',
        '"敵全体の足元を打ち抜き、バランスを崩させる。"' : '"Shoots at all enemy\'s footing and causes them to \\nlose balance."',
        '"スタンショット"' : '"Stun Shot"',
        '"敵単体に5回ダメージを与える。"' : '"Inflicts damage on an enemy 5 times."',
        '"チームショット"' : '"Team Shot"',
        '"敵全体に２回ダメージを与える。"' : '"Inflicts damage on all enemies 2 times."',
        '"レインショット"' : '"Rain Shot"',
        //'' : '',
   //other
        '"note"\:"スキル１番は［攻撃］コマンドを\\n選択したときに使用されます。"' : '"note"\:"Skill 1 will be used when you select\\nthe Attack command."',
        '"は身を守っている。"' : '" guards."',
        '"note"\:"スキル２番は［防御］コマンドを\\n選択したときに使用されます。"' : '"note"\:"Skill 2 will be used when you select\\nthe Guard command."',
        '"ヒール"' : '"Heal"',
        '"ファイア"' : '"Fire"',
        '"トランス"' : '"Trans"',
        '"コンセントレイト"' : '"Concentration"',
        //'' : '',
// Translations for States file
   //original
        '"は倒れた！"' : '" has fallen!"',
        '"を倒した！"' : '" is slain!"',
        '"は立ち上がった！"' : '" revives!"',
        '"戦闘不能"' : '"Dead"',
        '"ステート１番はＨＰが０になったときに\\n自動的に付加されます。"' : '"State 1 occurs automatically when HP \\nreaches 0."',
        //'"防御"' : '"Defense"',
        '"不死身"' : '"Immortal"',
        '"は毒にかかった！"' : '" is poisoned!"',
        '"に毒をかけた！"' : '" is poisoned!"',
        '"の毒が消えた！"' : '" is no longer poisoned!"',
        '"毒"' : '"Poison"',
        '"は暗闇に閉ざされた！"' : '" is blinded!"',
        '"を暗闇に閉ざした！"' : '" is blinded!"',
        '"の暗闇が消えた！"' : '" is no longer blinded!"',
        '"暗闇"' : '"Blind"',
        '"は沈黙した！"' : '" is silenced!"',
        '"を沈黙させた！"' : '" is silenced!"',
        '"の沈黙が解けた！"' : '" is no longer silenced!"',
        '"沈黙"' : '"Silence"',
        '"は激昂した！"' : '" is enraged!"',
        '"を激昂させた！"' : '" is enraged!"',
        '"激昂"' : '"Rage"',
        '"は混乱した！"' : '" is confused!"',
        '"を混乱させた！"' : '" is confused!"',
        '"混乱"' : '"Confusion"',
        '"は魅了された！"' : '" is fascinated!"',
        '"を魅了した！"' : '" is fascinated!"',
        '"魅了"' : '"Fascination"',
        '"は眠った！"' : '" falls asleep!"',
        '"を眠らせた！"' : '" falls asleep!"',
        '"は目を覚ました！"' : '" wakes up!"',
        '"睡眠"' : '"Sleep"',
        '"はしびれて動けなくなった！"' : '" is paralyzed and can\'t move!"',
        '"を麻痺させた！"' : '" is paralyzed!"',
        '"は体がしびれて動けない！"' : '" is paralyzed and can\'t move!"',
        '"の麻痺が解けた！"' : '" is no longer paralyzed!"',
        '"麻痺"' : '"Paralyze"',
        '"はバランスを崩した！"' : '" lost balance!"',
        '"はバランスを崩している……"' : '" is still off-balance..."',
        '"は体勢を立て直した！"' : '" regained balance!"',
        '"スタン"' : '"Stun"',
        '"HP再生"' : '"HP Regeneration"',
        '"MP再生"' : '"MP Regeneration"',
        '"TP再生"' : '"TP Regeneration"',
        '"魔法反射"' : '"Magic Reflection"',
        '"は狙われやすくなった！"' : '" became easier to hit!"',
        '"挑発"' : '"Provoke"',
        '"は狙われにくくなった！"' : '" became harder to hit!"',
        '"反撃"' : '"Counter Attack"',
        '"状態異常防止"' : '"Status Ailment Block"',
        '"消費MP減"' : '"Reduce MP Cost"',
        '"は炎の力を身にまとった。"' : '" is shrouded in the force of fire."',
        '"炎の力"' : '"Fire Force"',
        '"は氷の力を身にまとった。"' : '" is shrouded in the force of ice."',
        '"氷の力"' : '"Ice Force"',
        '"は雷の力を身にまとった。"' : '" is shrouded in the force of thunder."',
        '"雷の力"' : '"Thunder Force"',
        '"エンカウント半減"' : '"Encounter Half"',
        '"賞金・アイテム2倍"' : '"Double Money/Items"',
        //'' : '',
   //other
        '"は我に返った！"' : '" has come to senses!"',
        '"は眠っている。"' : '" is still sleeping..."',
        '"は麻痺して動けなくなった！"' : '" can\'t move!"',
        '"を麻痺で動けなくさせた！"' : '" can\'t move!"',
        '"は痺れていて動けない。"' : '" is still paralyzed!"',
        '"は麻痺から回復した！"' : '" can move again!"',
        //'' : '',
// Translations for Troops file
   //original
        '"name"\:"スライム' : '"name"\:"Slime',
        '"name"\:"ホーネット' : '"name"\:"Hornet',
        '　プラント"' : ' Demon Plant"',
        '"name"\:"プラント' : '"name"\:"Demon Plant',
        '"name"\:"キラーラット' : '"name"\:"Killer Rat',
        '"name"\:"バット' : '"name"\:"Bat',
        '"name"\:"スパイダー' : '"name"\:"Spider',
        '"name"\:"スネイク' : '"name"\:"Snake',
        '　スネイク"' : ' Snake"',
        '"name"\:"インプ' : '"name"\:"Imp',
        '　インプ"' : ' Imp"',
        '"name"\:"盗賊' : '"name"\:"Bandit',
        '"name"\:"オーク' : '"name"\:"Orc',
        //'' : '',
   //other
        '"name"\:"こうもり' : '"name"\:"Bat',
        '"name"\:"ミノタウロス' : '"name"\:"Minotaur',
        '"name"\:"エキドナ' : '"name"\:"Echidna',
        '"name"\:"ハーピー' : '"name"\:"Harpy',
        //'' : '',
// Translations for Weapons file
   //original
/*        '【剣】' : '[Sword] ',
        '【杖】' : '[Staff] ',
        '【フレイル】' : '[Flail] ',
        '【斧】' : '[Axe] ',
        '【槍】' : '"[Spear] ',
        '【グローブ】' : '[Glove] ',
        '【爪】' : '[Claw] ',
        '【弓】' : '[Bow] ',
        '【短剣】' : '[Dagger] ',
*/        '"【剣】' : '',
        '【杖】' : '',
        '【フレイル】' : '',
        '【斧】' : '',
        '【槍】' : '',
        '【グローブ】' : '',
        '【爪】' : '',
        '【弓】' : '',
        '【短剣】' : '',
        '軽くて扱いやすい刀身の短い剣。"' : 'A light and easy-to-wield short-bladed sword."',
        'ショートソード"' : 'Short Sword"',
        '鋭い切れ味を誇る戦闘用の長剣。"' : 'A long battle sword boasting a sharp cut."',
        'ロングソード"' : 'Long Sword"',
        '反りのある刀身をもつ幅広の剣。"' : 'A wide sword with a curved blade."',
        'ファルシオン"' : 'Falchion"',
        'ミスリルで作られた長剣。"' : 'A long sword forged of mithril."',
        'ミスリルソード"' : 'Mithril Sword"',
        'ドラゴンのキバで作られた剣。"' : 'A sword forged of dragon\'s fangs."',
        'ドラゴンブレード"' : 'Dragon Blade"',
        '安価で一般に普及している杖。"' : 'An inexpensive and widely-used staff."',
        'ウッドスタッフ"' : 'Wooden Staff"',
        '術者の魔力をやや増幅させる杖。"' : 'A wand that slightly increases its wielder\'s \\nmagical powers."',
        'マジックワンド"' : 'Magic Wand"',
        '術者の魔力を増幅させる銀製の杖。"' : 'A silver wand that increases its wielder\'s \\nmagical powers."',
        'フォースワンド"' : 'Force Wand"',
        '術者の魔力を増幅させるミスリルの杖。"' : 'A mithril rod that increases its wielder\'s \\nmagical powers."',
        'ミスリルロッド"' : 'Mithril Rod"',
        '術者の魔力を増幅させるドラゴンの杖。"' : 'A dragon staff that increases its wielder\'s \\nmagical powers."',
        'ドラゴンスタッフ"' : 'Dragon Staff"',
        '柄の先に鎖で石球をつないだ連接棍棒。"' : 'A flail with a stone head attached to its \\nhandle with a chain."',
        'ストーンフレイル"' : 'Stone Flail"',
        '柄の先に鎖で銅球をつないだ連接棍棒。"' : 'A flail with a bronze head attached to its \\nhandle with a chain."',
        'ブロンズフレイル"' : 'Bronze Flail"',
        '鋼鉄で強化した連接棍棒。"' : 'A flail fortified with iron steel."',
        'モーニングスター"' : 'Morning Star"',
        'ミスリルで強化した連接棍棒。"' : 'A flail fortified with mithril."',
        'ミスリルフレイル"' : 'Mithril Flail"',
        'ドラゴンのキバで強化した連接棍棒。"' : 'A flail fortified with dragon\'s fangs."',
        'ドラゴンフレイル"' : 'Dragon Flail"',
        '伐採に使う小型の斧。"' : 'A small axe used for logging trees."',
        'ハンドアクス"' : 'Hand Axe"',
        '戦闘用に作られた両刃の斧。"' : 'A double-edged axe made for battle."',
        'バトルアクス"' : 'Battle Axe"',
        '三日月型の刃をもつ戦斧。"' : 'A battle axe with a crescent-shaped blade."',
        'バルディッシュ"' : 'Bardiche"',
        'ミスリルで作られた戦斧。"' : 'A battle axe forged of mithril."',
        'ミスリルアスク"' : 'Mithril Axe"',
        'ドラゴンのキバで作られた戦斧。"' : 'A battle axe forged of dragon\'s fangs."',
        'ドラゴンアスク"' : 'Dragon Axe"',
        '突きに特化させた短めの槍。"' : 'A short spear specialized in thrusting."',
        'ショートスピア"' : 'Short Spear"',
        '柄を可能な限り長くした槍。"' : 'A spear with the longest handle possible."',
        'ロングスピア"' : 'Long Spear"',
        '穂先に斧頭の取りつけられた槍。"' : 'A spear with an axe-head at its tip."',
        'ハルバード"' : 'Halberd"',
        'ミスリルで作られた槍。"' : 'A spear forged of mithril."',
        'ミスリルスピア"' : 'Mithril Spear"',
        'ドラゴンのキバで作られた槍。"' : 'A spear forged of dragon\'s fangs."',
        'ドラゴンスピア"' : 'Dragon Spear"',
        '拳頭にトゲがついた格闘用のグローブ。"' : 'A battle glove with spikes attached to its \\nknuckles."',
        'セスタス"' : 'Cestus"',
        '短い４本の爪が取りつけられた格闘武器。"' : 'A combat weapon with 4 short claws attached."',
        'バグナウ"' : 'Bagh Naka"',
        '鋼鉄のかぎ爪が仕込まれた格闘武器。"' : 'A combat weapon with iron talons attached."',
        'アイアンクロウ"' : 'Iron Claw"',
        'ミスリルのかぎ爪が仕込まれた格闘武器。"' : 'A combat weapon with mithril talons attached."',
        'ミスリルクロウ"' : 'Mithril Claw"',
        'ドラゴンのかぎ爪が仕込まれた格闘武器。"' : 'A combat weapon with dragon talons attached."',
        'ドラゴンクロウ"' : 'Dragon Claw"',
        '狩猟用に作られた短めの弓。"' : 'A short bow made for hunting."',
        'ショートボウ"' : 'Short Bow"',
        '威力を高めた戦闘用の長弓。"' : 'A long bow for battle with superior power."',
        'ロングボウ"' : 'Long Bow"',
        '強力なバネで矢を射出する石弓。"' : 'A crossbow that shoots arrows with powerful \\nsprings."',
        '強力なバネでミスリルの矢を射出する石弓。"' : 'A crossbow that shoots mithril arrows with \\npowerful springs."',
        'ミスリルボウ"' : 'Mithril Bow"',
        'ドラゴンのヒゲで作られた戦闘用の長弓。"' : 'A long bow for battle made with dragon\'s \\nwhiskers."',
        'ドラゴンボウ"' : 'Dragon Bow"',
        '日常生活にも使えるナイフ。"' : 'A knife used for day-to-day tasks."',
        'ナイフ"' : 'Knife"',
        '戦闘用の短刀。"' : 'A short blade used for battle."',
        'ダガー"' : 'Daggar"',
        '刀身が厚く丈夫な短刀。"' : 'A dagger with a thick"',
        'マシェット"' : 'Machete"',
        'ミスリルで作られた短刀。"' : 'A dagger forged of mithril."',
        'ミスリルダガー"' : 'Mithril Daggar"',
        'ドラゴンのキバで作られた短刀。"' : 'A dagger forged of dragon\'s fangs"',
        'ドラゴンダガー"' : 'Dragon Daggar"',
        //'' : '',
   //other
        '"レイピア"' : '"Rapier"',
        '"ブロードソード"' : '"Broad sword"',
        '"フランベルジュ"' : '"Flamberge"',
        '"クレイモア"' : '"Claymore"',
        '"エストック"' : '"Estoc"',
        //'"アロンダイト"' : '',
        '"クラウソラス"' : '"Cutlass"',
        '"グラディウス"' : '"Gladius"',
        '"オブシダンソード"' : '"Obsidian Sword"',
        //'"ブレイブソード"' : '',
        '"バトルアックス"' : '"Battle Axe"',
        '"樫の杖"' : '"Wood Staff"',
        '"硬い樫の木で作られた杖。"' : '"A simple cane made from oak."',
        //'' : '',
      
    ///////////////////////////////////////////////////////
    '':''};











    //////////////////////////////////////////////////////////////////////////////
    // This is where the real code is
    // Don't edit below this
    //////////////////////////////////////////////////////////////////////////////

    var regexs = [], replacements = [],
        tagsWhitelist = ['INPUT', 'TEXTAREA'],
        rIsRegexp = /^\/(.+)\/([gim]+)?$/,
        word, text, texts, i, userRegexp;

    // prepareRegex by JoeSimmons
    // used to take a string and ready it for use in new RegExp()
    function prepareRegex(string) {
        return string.replace(/([\[\]\^\&\$\.\(\)\?\/\\\+\{\}\|])/g, '\\$1');
    }

    // function to decide whether a parent tag will have its text replaced or not
    function isTagOk(tag) {
        return tagsWhitelist.indexOf(tag) === -1;
    }

    delete words['']; // so the user can add each entry ending with a comma,
                      // I put an extra empty key/value pair in the object.
                      // so we need to remove it before continuing

    // convert the 'words' JSON object to an Array
    for (word in words) {
        if ( typeof word === 'string' && words.hasOwnProperty(word) ) {
            userRegexp = word.match(rIsRegexp);

            // add the search/needle/query
            if (userRegexp) {
                regexs.push(
                    new RegExp(userRegexp[1], 'g')
                );
            } else {
                regexs.push(
                    new RegExp(prepareRegex(word).replace(/\\?\*/g, function (fullMatch) {
                        return fullMatch === '\\*' ? '*' : '[^ ]*';
                    }), 'g')
                );
            }

            // add the replacement
            replacements.push( words[word] );
        }
    }

    // do the replacement
    texts = document.evaluate('//body//text()[ normalize-space(.) != "" ]', document, null, 6, null);
    for (i = 0; text = texts.snapshotItem(i); i += 1) {
        if ( isTagOk(text.parentNode.tagName) ) {
            regexs.forEach(function (value, index) {
                text.data = text.data.replace( value, replacements[index] );
            });
        }
    }

}());
