// ==UserScript==
// @name           RPG Maker MV part trans
// @namespace      http://userscripts.org/users/23652
// @description    Replaces Japanese text for RPG Maker MV json files
// @include        file://localhost/*/*.json
// @grant          none
// @copyright      JoeSimmons
// @version        1.2.1
// @project page   https://github.com/Anon7404/DLStrans/tree/MV-partial-translation
// @downloadURL    https://raw.github.com/Anon7404/DLStrans/MV-partial-translation/RPG_Maker_MV_part_trans.user.js
// @updateURL      https://raw.github.com/Anon7404/DLStrans/MV-partial-translation/RPG_Maker_MV_part_trans.user.js
// ==/UserScript==
(function () {
    'use strict';


    /*
        NOTE: 
            You can use \\* to match actual asterisks instead of using it as a wildcard!
            The examples below show a wildcard in use and a regular asterisk replacement.
    */

    var words = {
    ///////////////////////////////////////////////////////


        // Syntax: 'Search word' : 'Replace word',
// Automatic line separator, remove /* and */ for it to work
/*        '"\,"' : '",\n"',
        '}\,{' : '},\n{',
        '"]\,"' : '"],\n"',
        '\,"description"\:"' : '\,\n"description"\:"',
        '\,"name"\:"' : '\,\n"name"\:"',
        '\,"message1"\:"' : '\,\n"message1"\:"',
*/        //'' : '',
// Original RPG MV files
// [Actors.json]
        '"name"\:"ハロルド"' : '"name"\:"Harold"',
        '"name"\:"テレーゼ"' : '"name"\:"Therese"',
        '"name"\:"マーシャ"' : '"name"\:"Marsha"',
        '"name"\:"ルキウス"' : '"name"\:"Lucius"',
        '"name"\:"フレッド"' : '"name"\:"Fred"',
        '"name"\:"イリア"' : '"name"\:"Ilia"',
        '"name"\:"ヴァイス"' : '"name"\:"Vice"',
        '"name"\:"エリザ"' : '"name"\:"Eliza"',
// non-original
        '"name"\:"ユイ"' : '"name"\:"Yui"',
//        '' : '',
// [Armors.json]
        '"name"\:"------------鎧系"' : '"name"\:"------------Armors"',
        '"【一般装備】通気性の高い布の服。"' : '"\[General Equipment\] Linen clothing with high \\nbreathability. "',
        '"通気性の高い布の服。"' : '"Linen clothing with high \\nbreathability. "',
        '"name"\:"布の服"' : '"name"\:"Linen Clothing"',
        '"【一般装備】なめし皮で作られたベスト。"' : '"\[General Equipment\] A vest made of tanned hide."',
        '"なめし皮で作られたベスト。"' : '"A vest made of tanned hide."',
        '"name"\:"レザーベスト"' : '"name"\:"Leather Vest"',
        '"【一般装備】過酷な旅にも耐えられる丈夫な服。"' : '"\[General Equipment\] Durable clothing that can \\nwithstand rough travels."',
        '"過酷な旅にも耐えられる丈夫な服。"' : '"Durable clothing that can \\nwithstand rough travels."',
        '"name"\:"冒険者の服"' : '"name"\:"Adventurer\'s Clothing"',
        '"【一般装備】にかわで固めた硬皮のベスト。"' : '"\[General Equipment\] A vest made of leather \\nhardened with glue."',
        '"にかわで固めた硬皮のベスト。"' : '"A vest made of leather \\nhardened with glue."',
        '"name"\:"ハードレザー"' : '"name"\:"Hard Leather"',
        '"【一般装備】鋼板で補強したなめし皮製の服。"' : '"\[General Equipment\] Tanned hide clothing reinforced \\nwith steel plates."',
        '"鋼板で補強したなめし皮製の服。"' : '"Tanned hide clothing reinforced \\nwith steel plates."',
        '"name"\:"ブリガンダイン"' : '"name"\:"Brigandine"',
        '"【軽装備】丈夫な布で作られた鎧。"' : '"\[Light Equipment\] Armor made of tough cloth. "',
        '"丈夫な布で作られた鎧。"' : '"Armor made of tough cloth. "',
        '"name"\:"クロースアーマー"' : '"name"\:"Cloth Armor"',
        '"【軽装備】なめし皮を重ねて組んだ鎧。"' : '"\[Light Equipment\] Armor made of layered hide. "',
        '"なめし皮を重ねて組んだ鎧。"' : '"Armor made of layered hide. "',
        '"name"\:"レザーアーマー"' : '"name"\:"Leather Armor"',
        '"【軽装備】青銅製の胸当て。"' : '"\[Light Equipment\] A breastplate made of bronze. "',
        '"青銅製の胸当て。"' : '"A breastplate made of bronze. "',
        '"name"\:"ブロンズブレスト"' : '"name"\:"Bronze Breastplate"',
        '"【軽装備】鋼鉄製の胸当て。"' : '"\[Light Equipment\] A breastplate made of iron steel."',
        '"鋼鉄製の胸当て。"' : '"A breastplate made of iron steel."',
        '"name"\:"アイアンブレスト"' : '"name"\:"Iron Breastplate"',
        '"【軽装備】ミスリルで作られた胸当て。"' : '"\[Light Equipment\] A breastplate made of mithril."',
        '"ミスリルで作られた胸当て。"' : '"A breastplate made of mithril."',
        '"name"\:"ミスリルブレスト"' : '"name"\:"Mithril Breastplate"',
        '"【軽装備】ドラゴンの鱗作られた胸当て。"' : '"\[Light Equipment\] A breastplate made of dragon scales."',
        '"ドラゴンの鱗作られた胸当て。"' : '"A breastplate made of dragon scales."',
        '"name"\:"ドラゴンブレスト"' : '"name"\:"Dragon Breastplate"',
        '"【重装備】青銅製の鎧。"' : '"\[Heavy Equipment\] Armor made of bronze."',
        '"青銅製の鎧。"' : '"Armor made of bronze."',
        '"name"\:"ブロンズアーマー"' : '"name"\:"Bronze Armor"',
        '"【重装備】鋼鉄製の鎧。"' : '"\[Heavy Equipment\] Armor made of iron steel."',
        '"鋼鉄製の鎧。"' : '"Armor made of iron steel."',
        '"name"\:"アイアンアーマー"' : '"name"\:"Iron Armor"',
        '"【重装備】ミスリルで作られた鎧。"' : '"\[Heavy Equipment\] Armor made of mithril."',
        '"ミスリルで作られた鎧。"' : '"Armor made of mithril."',
        '"name"\:"ミスリルアーマー"' : '"name"\:"Mithril Armor"',
        '"【重装備】ドラゴンの鱗で作られた鎧。"' : '"\[Heavy Equipment\] Armor made of dragon scales."',
        '"ドラゴンの鱗で作られた鎧。"' : '"Armor made of dragon scales."',
        '"name"\:"ドラゴンアーマー"' : '"name"\:"Dragon Armor"',
        '"【魔法装備】広く普及している一般的なローブ。"' : '"\[Magic Equipment\] A basic, widely prevalent robe. "',
        '"広く普及している一般的なローブ。"' : '"A basic, widely prevalent robe. "',
        '"name"\:"木綿のローブ"' : '"name"\:"Cotton Robe"',
        '"【魔法装備】絹で作られた上質なマント。"' : '"\[Magic Equipment\] A high-quality cloak made of silk."',
        '"絹で作られた上質なマント。"' : '"A high-quality cloak made of silk."',
        '"name"\:"絹のマント"' : '"name"\:"Silk Cloak"',
        '"【魔法装備】ルーン文字が刻まれたローブ。"' : '"\[Magic Equipment\] A robe inscribed with runic letters."',
        '"ルーン文字が刻まれたローブ。"' : '"A robe inscribed with runic letters."',
        '"name"\:"術士のローブ"' : '"name"\:"Tactician\'s Robe"',
        '"【魔法装備】魔力が織り込まれたローブ。"' : '"\[Magic Equipment\] A robe interwoven with magical \\npowers. "',
        '"魔力が織り込まれたローブ。"' : '"A robe interwoven with magical \\npowers. "',
        '"name"\:"賢者のローブ"' : '"name"\:"Sage\'s Robe"',
        '"【魔法装備】精霊王の力が宿る究極のマント。"' : '"\[Magic Equipment\] A cloak that houses the power of \\nspirits."',
        '"精霊王の力が宿る究極のマント。"' : '"A cloak that houses the power of \\nspirits."',
        '"name"\:"エレメンタルマント"' : '"name"\:"Elemental Cloak"',
        '"name"\:"------------盾系"' : '"name"\:"------------Shields"',
        '"【小型盾】攻撃を受け流すための小型盾。"' : '"\[Small Shield\] A small shield for deflecting attacks."',
        '"攻撃を受け流すための小型盾。"' : '"A small shield for deflecting attacks."',
        '"name"\:"バックラー"' : '"name"\:"Buckler"',
        '"【小型盾】鉄の枠で補強した木製の円盾。"' : '"\[Small Shield\] A round, wooden shield reinforced \\nwith an iron frame. "',
        '"鉄の枠で補強した木製の円盾。"' : '"A round, wooden shield reinforced \\nwith an iron frame. "',
        '"name"\:"ラウンドバックラー"' : '"name"\:"Round Buckler"',
        '"【小型盾】表面に攻撃用のトゲがついた円盾。"' : '"\[Small Shield\] A round shield with attack spikes \\nattached. "',
        '"表面に攻撃用のトゲがついた円盾。"' : '"A round shield with attack spikes \\nattached. "',
        '"name"\:"スパイクバックラー"' : '"name"\:"Spiked Buckler"',
        '"【小型盾】ミスリルで作られた小型盾。"' : '"\[Small Shield\] A small shield made of mithril."',
        '"ミスリルで作られた小型盾。"' : '"A small shield made of mithril."',
        '"name"\:"ミスリルバックラー"' : '"name"\:"Mithril Buckler"',
        '"【小型盾】竜の鱗から作られた小型盾。"' : '"\[Small Shield\] A small shield made of dragon scales."',
        '"竜の鱗から作られた小型盾。"' : '"A small shield made of dragon scales."',
        '"name"\:"ドラゴンバックラー"' : '"name"\:"Dragon Buckler"',
        '"【大型盾】ごく普通の木製の大きな盾。"' : '"\[Large Shield\] A large, average wooden shield. "',
        '"ごく普通の木製の大きな盾。"' : '"A large, average wooden shield. "',
        '"name"\:"ウッドシールド"' : '"name"\:"Wooden Shield"',
        '"【大型盾】青銅の板で作られた大きな盾。"' : '"\[Large Shield\] A large shield made of bronze plates. "',
        '"青銅の板で作られた大きな盾。"' : '"A large shield made of bronze plates. "',
        '"name"\:"ブロンズシールド"' : '"name"\:"Bronze Shield"',
        '"【大型盾】鋼鉄製の大きな盾。"' : '"\[Large Shield\] A large shield made of iron steel."',
        '"鋼鉄製の大きな盾。"' : '"A large shield made of iron steel."',
        '"name"\:"アイアンシールド"' : '"name"\:"Iron Shield"',
        '"【大型盾】ミスリルで作られた大型の盾"' : '"\[Large Shield\] A large shield made of mithril."',
        '"ミスリルで作られた大型の盾"' : '"A large shield made of mithril."',
        '"name"\:"ミスリルシールド"' : '"name"\:"Mithril Shield"',
        '"【大型盾】竜の鱗から作られた大型の盾。"' : '"\[Large Shield\] A large shield made of dragon scales."',
        '"竜の鱗から作られた大型の盾。"' : '"A large shield made of dragon scales."',
        '"name"\:"ドラゴンシールド"' : '"name"\:"Dragon Shield"',
        '"【魔法装備】守護の魔法がかけられた腕輪。"' : '"\[Magic Equipment\] A bangle enchanted with protective \\nmagic."',
        '"守護の魔法がかけられた腕輪。"' : '"A bangle enchanted with protective \\nmagic."',
        '"name"\:"ウッドバングル"' : '"name"\:"Wooden Bangle"',
        '"name"\:"ブロンズバングル"' : '"name"\:"Bronze Bangle"',
        '"name"\:"アイアンバングル"' : '"name"\:"Iron Bangle"',
        '"name"\:"ミスリルバングル"' : '"name"\:"Mithril Bangle"',
        '"name"\:"ドラゴンバングル"' : '"name"\:"Dragon Bangle"',
        '"name"\:"------------兜系"' : '"name"\:"------------Helmets"',
        '"【一般装備】額を守る布製のハチマキ。"' : '"\[General Equipment\] A cloth headband for protecting \\nthe forehead. "',
        '"額を守る布製のハチマキ。"' : '"A cloth headband for protecting \\nthe forehead. "',
        '"name"\:"バンダナ"' : '"name"\:"Bandana"',
        '"【一般装備】額を守る皮製のハチマキ。"' : '"\[General Equipment\] A leather headband for protecting \\nthe forehead."',
        '"額を守る皮製のハチマキ。"' : '"A leather headband for protecting \\nthe forehead."',
        '"name"\:"レザーバンダナ"' : '"name"\:"Leather Bandana"',
        '"【一般装備】皮で作られた帽子。"' : '"\[General Equipment\] A hat made of leather. "',
        '"皮で作られた帽子。"' : '"A hat made of leather. "',
        '"name"\:"皮の帽子"' : '"name"\:"Leather Hat"',
        '"【一般装備】重ねて巻きつけて頭を守る厚手の布。"' : '"\[General Equipment\] A thick cloth layered and wrapped \\naround the head for protection."',
        '"重ねて巻きつけて頭を守る厚手の布。"' : '"A thick cloth layered and wrapped \\naround the head for protection."',
        '"name"\:"ターバン"' : '"name"\:"Turban"',
        '"【一般装備】鳥の羽がついたオシャレな帽子。"' : '"\[General Equipment\] A fancy hat with bird feathers \\nattached."',
        '"鳥の羽がついたオシャレな帽子。"' : '"A fancy hat with bird feathers \\nattached."',
        '"name"\:"羽根付き帽子"' : '"name"\:"Feathered Hat"',
        '"【軽装備】なめし皮で作られた帽子。"' : '"\[Light Equipment\] A hat made of tanned hide."',
        '"なめし皮で作られた帽子。"' : '"A hat made of tanned hide."',
        '"name"\:"レザーキャップ"' : '"name"\:"Leather Cap"',
        '"【軽装備】木で作られた軽量のヘルメット。"' : '"\[Light Equipment\] A light helmet made of wood. "',
        '"木で作られた軽量のヘルメット。"' : '"A light helmet made of wood. "',
        '"name"\:"ウッドキャップ"' : '"name"\:"Wooden Cap"',
        '"【軽装備】銅板で強化された軽量のヘルメット。"' : '"\[Light Equipment\] A light helmet reinforced with \\nbronze plates."',
        '"銅板で強化された軽量のヘルメット。"' : '"A light helmet reinforced with \\nbronze plates."',
        '"name"\:"ブロンズキャップ"' : '"name"\:"Bronze Cap"',
        '"【軽装備】鉄板で強化された軽量のヘルメット。"' : '"\[Light Equipment\] A light helmet reinforced with \\niron plates."',
        '"鉄板で強化された軽量のヘルメット。"' : '"A light helmet reinforced with \\niron plates."',
        '"name"\:"アイアンキャップ"' : '"name"\:"Iron Cap"',
        '"【軽装備】ミスリルで強化された軽量のヘルメット。"' : '"\[Light Equipment\] A light helmet reinforced with \\nmithril."',
        '"ミスリルで強化された軽量のヘルメット。"' : '"A light helmet reinforced with \\nmithril."',
        '"name"\:"ミスリルキャップ"' : '"name"\:"Mithril Cap"',
        '"【軽装備】ドラゴンの鱗で強化された軽量のヘルメット。"' : '"\[Light Equipment\] A light helmet reinforced with \\ndragon scales."',
        '"ドラゴンの鱗で強化された軽量のヘルメット。"' : '"A light helmet reinforced with \\ndragon scales."',
        '"name"\:"ドラゴンキャップ"' : '"name"\:"Dragon Cap"',
        '"【重装備】細かい鎖を編んで作られた頭巾。"' : '"\[Heavy Equipment\] A hood made with fine, woven chains."',
        '"細かい鎖を編んで作られた頭巾。"' : '"A hood made with fine, woven chains."',
        '"name"\:"チェインコイフ"' : '"name"\:"Chainmail Coif"',
        '"【重装備】厚い青銅の板で作られた兜。"' : '"\[Heavy Equipment\] A helmet made with thick bronze \\nplates. "',
        '"厚い青銅の板で作られた兜。"' : '"A helmet made with thick bronze \\nplates. "',
        '"name"\:"ブロンズヘルム"' : '"name"\:"Bronze Helm"',
        '"【重装備】厚い鋼鉄の板で作られた兜。"' : '"\[Heavy Equipment\] A helmet made with thick iron\\nplates. "',
        '"厚い鋼鉄の板で作られた兜。"' : '"A helmet made with thick iron\\nplates. "',
        '"name"\:"アイアンヘルム"' : '"name"\:"Iron Helm"',
        '"【重装備】ミスリルで作られた兜。"' : '"\[Heavy Equipment\] A helmet made of mithril."',
        '"ミスリルで作られた兜。"' : '"A helmet made of mithril."',
        '"name"\:"ミスリルヘルム"' : '"name"\:"Mithril Helm"',
        '"【重装備】ドラゴンの鱗で作られた兜。"' : '"\[Heavy Equipment\] A helmet made with dragon scales."',
        '"ドラゴンの鱗で作られた兜。"' : '"A helmet made with dragon scales."',
        '"name"\:"ドラゴンヘルム"' : '"name"\:"Dragon Helm"',
        '"【魔法装備】なめし皮で作られたつばの広い三角の帽子。"' : '"\[Magic Equipment\] A triangular, tanned hide hat with \\na wide brim. "',
        '"なめし皮で作られたつばの広い三角の帽子。"' : '"A triangular, tanned hide hat with \\na wide brim. "',
        '"name"\:"とんがり帽子"' : '"name"\:"Pointed Hat"',
        '"【魔法装備】守護の魔法がかけられた簡素な冠。"' : '"\[Magic Equipment\] A simple crown enchanted with \\nprotective magic."',
        '"守護の魔法がかけられた簡素な冠。"' : '"A simple crown enchanted with \\nprotective magic."',
        '"name"\:"サークレット"' : '"name"\:"Circlet"',
        '"【魔法装備】守護の魔法がかけられた銀細工の冠。"' : '"\[Magic Equipment\] A silver crown enchanted with \\nprotective magic."',
        '"守護の魔法がかけられた銀細工の冠。"' : '"A silver crown enchanted with \\nprotective magic."',
        '"name"\:"シルバーサークレット"' : '"name"\:"Silver Circlet"',
        '"【魔法装備】守護の魔法がかけられた純金の冠。"' : '"\[Magic Equipment\] A pure gold crown enchanted with \\nprotective magic."',
        '"守護の魔法がかけられた純金の冠。"' : '"A pure gold crown enchanted with \\nprotective magic."',
        '"name"\:"ゴールドサークレット"' : '"name"\:"Gold Circlet"',
        '"【魔法装備】守護の魔法がかけられたミスリルの冠。"' : '"\[Magic Equipment\] A mithril crown enchanted with \\nprotective magic."',
        '"守護の魔法がかけられたミスリルの冠。"' : '"A mithril crown enchanted with \\nprotective magic."',
        '"name"\:"ミスリルサークレット"' : '"name"\:"Mithril Circlet"',
        '"【魔法装備】守護の魔法がかけられた賢者の冠。"' : '"\[Magic Equipment\] A sage\'s crown enchanted with \\nprotective magic."',
        '"守護の魔法がかけられた賢者の冠。"' : '"A sage\'s crown enchanted with \\nprotective magic."',
        '"name"\:"マスターサークレット"' : '"name"\:"Master Circlet"',
        '"name"\:"------------装飾品系"' : '"name"\:"------------Accessories"',
        '"【装飾品】防御力を高めてくれるお守り。"' : '"\[Accessory\] A charm that increases defense. "',
        '"防御力を高めてくれるお守り。"' : '"A charm that increases defense. "',
        '"name"\:"ガードストーン"' : '"name"\:"Guard Stone"',
        '"【装飾品】防御力を高めてくれる指輪。"' : '"\[Accessory\] A ring that increases defense."',
        '"防御力を高めてくれる指輪。"' : '"A ring that increases defense."',
        '"name"\:"ガードリング"' : '"name"\:"Guard Ring"',
        '"【装飾品】攻撃力を高めてくれるお守り。"' : '"\[Accessory\] A charm that increases attack."',
        '"攻撃力を高めてくれるお守り。"' : '"A charm that increases attack."',
        '"name"\:"パワーストーン"' : '"name"\:"Power Stone"',
        '"【装飾品】攻撃力を高めてくれる指輪。"' : '"\[Accessory\] A ring that increases attack."',
        '"攻撃力を高めてくれる指輪。"' : '"A ring that increases attack."',
        '"name"\:"パワーリング"' : '"name"\:"Power Ring"',
        '"【装飾品】敏捷性を高めてくれるお守り。"' : '"\[Accessory\] A charm that increases agility."',
        '"敏捷性を高めてくれるお守り。"' : '"A charm that increases agility."',
        '"name"\:"スピードストーン"' : '"name"\:"Speed Stone"',
        '"【装飾品】敏捷性を高めてくれる指輪。"' : '"\[Accessory\] A ring that increases agility."',
        '"敏捷性を高めてくれる指輪。"' : '"A ring that increases agility."',
        '"name"\:"スピードリング"' : '"name"\:"Speed Ring"',
        '"【装飾品】運を高めてくれるお守り。"' : '"\[Accessory\] A charm that increases luck."',
        '"運を高めてくれるお守り。"' : '"A charm that increases luck."',
        '"name"\:"ラッキーストーン"' : '"name"\:"Lucky Stone"',
        '"【装飾品】運を高めてくれる指輪。"' : '"\[Accessory\] A ring that increases luck."',
        '"運を高めてくれる指輪。"' : '"A ring that increases luck."',
        '"name"\:"ラッキーリング"' : '"name"\:"Lucky Ring"',
        '"【装飾品】魔法力を高めてくれるお守り。"' : '"\[Accessory\] A charm that increases M.Attack."',
        '"魔法力を高めてくれるお守り。"' : '"A charm that increases M.Attack."',
        '"name"\:"マジカルストーン"' : '"name"\:"Magical Stone"',
        '"【装飾品】魔法力を高めてくれる指輪。"' : '"\[Accessory\] A ring that increases M.Attack."',
        '"魔法力を高めてくれる指輪。"' : '"A ring that increases M.Attack."',
        '"name"\:"マジカルリング"' : '"name"\:"Magical Ring"',
        '"【装飾品】攻撃の命中率を高めてくれるお守り。"' : '"\[Accessory\] A charm that increases the hit rate of \\nattacks."',
        '"攻撃の命中率を高めてくれるお守り。"' : '"A charm that increases the hit rate of \\nattacks."',
        '"name"\:"シューターストーン"' : '"name"\:"Shooter Stone"',
        '"name"\:"シューターリング"' : '"name"\:"Shooter Ring"',
        '"【装飾品】魔力の消費を20％抑えてくれるお守り。"' : '"\[Accessory\] A charm that reduces magic cost by 20%."',
        '"魔力の消費を20％抑えてくれるお守り。"' : '"A charm that reduces magic cost by 20%."',
        '"name"\:"マスターストーン"' : '"name"\:"Master Stone"',
        '"【装飾品】魔力の消費を50％抑えてくれる指輪。"' : '"\[Accessory\] A ring that reduces magic cost by 50%."',
        '"魔力の消費を50％抑えてくれる指輪。"' : '"A ring that reduces magic cost by 50%."',
        '"name"\:"マスターリング"' : '"name"\:"Master Ring"',
        '"【装飾品】毒・麻痺に、かかりにくくなる指輪。"' : '"\[Accessory\] A ring that helps prevent poisoned and \\nparalyzed states. "',
        '"毒・麻痺に、かかりにくくなる指輪。"' : '"A ring that helps prevent poisoned and \\nparalyzed states. "',
        '"name"\:"ポイズンガード"' : '"name"\:"Poison Guard"',
        '"【装飾品】毒・麻痺を完全に防ぐ指輪。"' : '"\[Accessory\] A ring that entirely prevents poisoned \\nand paralyzed states."',
        '"毒・麻痺を完全に防ぐ指輪。"' : '"A ring that entirely prevents poisoned \\nand paralyzed states."',
        '"name"\:"ポイズンガードＳ"' : '"name"\:"Super Poison Guard"',
        '"【装飾品】睡眠・沈黙・混乱・魅了・激昂に\\nかかりにくくなる指輪。"' : '"\[Accessory\] A ring that helps prevent sleep, \\nsilence, confusion, fascination, and rage states. "',
        '"睡眠・沈黙・混乱・魅了・激昂に\\nかかりにくくなる指輪。"' : '"A ring that helps prevent sleep, \\nsilence, confusion, fascination, and rage states. "',
        '"name"\:"メンタルガード"' : '"name"\:"Mental Guard"',
        '"【装飾品】睡眠・沈黙・混乱・魅了・激昂を\\n完全に防ぐ指輪。"' : '"\[Accessory\] A ring that entirely prevents sleep, \\nsilence, confusion, fascination, and rage states. "',
        '"睡眠・沈黙・混乱・魅了・激昂を\\n完全に防ぐ指輪。"' : '"A ring that entirely prevents sleep, \\nsilence, confusion, fascination, and rage states. "',
        '"name"\:"メンタルガードＳ"' : '"name"\:"Super Mental Guard"',
        '"【装飾品】先制攻撃を行える確率を上げます。"' : '"\[Accessory\] Raises the chance of performing a \\npreemptive attack."',
        '"先制攻撃を行える確率を上げます。"' : '"Raises the chance of performing a \\npreemptive attack."',
        '"name"\:"エネミーレーダー"' : '"name"\:"Enemy Radar"',
        '"【装飾品】不意打ち攻撃を受けなくなります。"' : '"\[Accessory\] Prevents surprise attacks. "',
        '"不意打ち攻撃を受けなくなります。"' : '"Prevents surprise attacks. "',
        '"name"\:"ワーニングベル"' : '"name"\:"Warning Bell"',
        '"【装飾品】ＴＰを次の戦闘に持ち越せるようになります。"' : '"\[Accessory\] Allows you to carryover TP over into the \\nnext battle."',
        '"ＴＰを次の戦闘に持ち越せるようになります。"' : '"Allows you to carryover TP over into the \\nnext battle."',
        '"name"\:"ＴＰストッカー"' : '"name"\:"Stocker"',
        '"【装飾品】ＴＰのチャージ率が上昇します。"' : '"\[Accessory\] Increases TP charge rate."',
        '"ＴＰのチャージ率が上昇します。"' : '"Increases TP charge rate."',
        '"name"\:"ガッツリング"' : '"name"\:"Ring of Guts"',
        '"【装飾品】ＭＰの消費率を下げます。"' : '"\[Accessory\] Decreases MP cost rate."',
        '"ＭＰの消費率を下げます。"' : '"Decreases MP cost rate."',
        '"name"\:"ＭＰキーパー"' : '"name"\:"MP Keeper"',
        '"【装飾品】四大精霊の加護のもと\\n火、水、風、土属性攻撃で受けるダメージを半減する。"' : '"\[Accessory\] Damage inflicted by water, fire, wind, \\nand earth attacks is halved. "',
        '"四大精霊の加護のもと\\n火、水、風、土属性攻撃で受けるダメージを半減する。"' : '"Damage inflicted by water, fire, wind, \\nand earth attacks is halved. "',
        '"name"\:"エレメンタルガード"' : '"name"\:"Elemental Guard"',
//'none decsr 1' : '"\[Accessory\] Sharpens eyesight and increases hit rate."',
//'none descr 2' : '"Sharpens eyesight and increases hit rate."',
//'none name 1' : '"name"\:"Spectacles"',
// other original
        '"name"\:"帽子"' : '"name"\:"Hat"',
        '"name"\:"服"' : '"name"\:"Cloth"',
        '"name"\:"指輪"' : '"name"\:"Ring"',
// non-original
        '"name"\:"ブリュンヒルデ"' : '"name"\:"Brünnhilde"',
        '"name"\:"オルトリンデ"' : '"name"\:"Ortlinde"',
        '"name"\:"ジークルーネ"' : '"name"\:"Siegrune"',
        '"name"\:"ヴァルトラウテ"' : '"name"\:"Waltraute"',
//        '' : '',
// [Classes.json]
        '"name"\:"剣士"' : '"name"\:"Swordsman"',
        '"name"\:"魔法使い"' : '"name"\:"Sorcerer"',
        '"name"\:"僧侶"' : '"name"\:"Priest"',
        '"name"\:"騎士"' : '"name"\:"Knight"',
        '"name"\:"格闘家"' : '"name"\:"Martial Artist"',
        '"name"\:"魔法剣士"' : '"name"\:"Magic Swordsman"',
        '"name"\:"狩人"' : '"name"\:"Hunter"',
        '"name"\:"盗賊"' : '"name"\:"Bandit"',
// other original
        '"name"\:"魔術師"' : '"name"\:"Mage"',
        '"name"\:"勇者"' : '"name"\:"Hero"',
        '"name"\:"戦士"' : '"name"\:"Warrior"',
//        '' : '',
// [Enemies.json]
        '"name"\:"スライム"' : '"name"\:"Slime"',
        '"name"\:"ホーネット"' : '"name"\:"Hornet"',
        '"name"\:"デビルプラント"' : '"name"\:"Demon Plant"',
        '"name"\:"キラーラット"' : '"name"\:"Killer Rat"',
        '"name"\:"スパイダー"' : '"name"\:"Spider"',
        '"name"\:"バット"' : '"name"\:"Bat"',
        '"name"\:"スネイク"' : '"name"\:"Snake"',
        '"name"\:"インプ"' : '"name"\:"Imp"',
        '"name"\:"ミミック"' : '"name"\:"Mimic"',
        '"name"\:"オーク"' : '"name"\:"Orc"',
// other original
        '"name"\:"ミノタウロス"' : '"name"\:"Minotaur"',
// non-original
        '"name"\:"こうもり"' : '"name"\:"Bat"',
        '"name"\:"エキドナ"' : '"name"\:"Echidna"',
        '"name"\:"ハーピー"' : '"name"\:"Harpy"',
        '"name"\:"兵士"' : '"name"\:"Soldier"',
        '"name"\:"ドライアド"' : '"name"\:"Dryad"',
        '"name"\:"雪女"' : '"name"\:"Yuki-onna"',
        '"name"\:"氷の精霊"' : '"name"\:"Ice Spirit"',
        '"name"\:"女王"' : '"name"\:"Queen"',
        '"name"\:"ダークエルフ"' : '"name"\:"Dark Elf"',
        '"name"\:"サキュバス"' : '"name"\:"Succubus"',
        '"name"\:"姫"' : '"name"\:"Princess"',
//        '' : '',
// [Items.json]
        '"回復アイテムより上位に表示したいアイテム用の枠です。"' : '"Below are spaces for when you would like to display \\nitems above the recovery items."',
        '"name"\:"-----予備"' : '"name"\:"-----Spare"',
        '"name"\:"-----回復系"' : '"name"\:"-----Recovery Items"',
        '"ＨＰを５００ポイント回復する。"' : '"Recovers HP by 500 points."',
        '"name"\:"ポーション"' : '"name"\:"Potion"',
        '"ＨＰを1５００ポイント回復する。"' : '"Recovers HP by 1500 points."',
        '"name"\:"ハイポーション"' : '"name"\:"Super Potion"',
        '"ＨＰを完全に回復する。"' : '"Completely recovers HP."',
        '"name"\:"フルポーション"' : '"name"\:"Full Potion"',
        '"ＭＰを３００ポイント回復する。"' : '"Recovers MP by 300 points."',
        '"name"\:"マジックウォーター"' : '"name"\:"Magic Water"',
        '"戦闘不能から復活させる。（ＨＰ半分回復）"' : '"Raises the user from the dead. (Recovers HP by half.)"',
        '"name"\:"スティミュラント"' : '"name"\:"Stimulant"',
        '"戦闘不能以外の状態異常を回復する。"' : '"Heals the user of status ailments besides dead."',
        '"name"\:"ディスペルハーブ"' : '"name"\:"Dispel Herb"',
        '"note"\:"ステートが増えたら追加する事。"' : '"note"\:"Add when states increase."',
        '"毒、麻痺、しびれ状態を治療する。"' : '"Cures poisoned, paralyzed, or stunned states."',
        '"name"\:"アンチドーテ"' : '"name"\:"Antidote"',
        '"ＨＰとＭＰを半分回復する。"' : '"Recovers HP and MP by half"',
        '"name"\:"ミラクルドロップ"' : '"name"\:"Miracle Drop"',
        '"ＨＰとＭＰを完全に回復する。"' : '"Completely recovers HP and MP."',
        '"name"\:"エリクサー"' : '"name"\:"Elixir"',
        '"name"\:"----特殊系"' : '"name"\:"----Specialty Items"',
        '"しばらくの間、敵との遭遇率を半減させる。"' : '"Halves the number of enemy encounters for a while. "',
        '"name"\:"エンカウントダウナー"' : '"name"\:"Encounter Decreaser"',
        '"しばらくの間\\n戦闘で得られるアイテムや賞金の獲得率を上げる。"' : '"Increases items and money gained from battle for \\na while."',
        '"name"\:"ドロップアッパー"' : '"name"\:"Drop Increaser"',
        '"name"\:"----強化系"' : '"name"\:"----Enhancement Items"',
        '"最大ＨＰを５０ポイント上げる。"' : '"Increases max HP by 50 points."',
        '"name"\:"ライフアップ"' : '"name"\:"Life Increase"',
        '"最大ＭＰを１０ポイント上げる。"' : '"Increases max HP by 10 points."',
        '"name"\:"マナアップ"' : '"name"\:"MP Increase"',
        '"攻撃力を３ポイント上げる。"' : '"Increases attack by 3 points."',
        '"name"\:"パワーアップ"' : '"name"\:"Power Increase"',
        '"防御力を３ポイント上げる。"' : '"Increases defense by 3 points."',
        '"name"\:"ガードアップ"' : '"name"\:"Guard Increase"',
        '"魔法力を３ポイント上げる。"' : '"Increases M.Attack by 3 points."',
        '"name"\:"マジックアップ"' : '"name"\:"Magic Increase"',
        '"魔法防御力を３ポイント上げる。"' : '"Increases M.Defense by 3 points."',
        '"name"\:"レジストアップ"' : '"name"\:"Resistance Increase"',
        '"敏捷性を３ポイント上げる。"' : '"Increases agility by 3 points."',
        '"name"\:"スピードアップ"' : '"name"\:"Speed Increase"',
        '"運を３ポイント上げる。"' : '"Increases luck by 3 points."',
        '"name"\:"ラックアップ"' : '"name"\:"Luck Increase"',
// non-original
        '"name"\:"マナポーション"' : '"name"\:"Mana Potion"',
        '"name"\:"ハイマナポーション"' : '"name"\:"High-Mana Potion"',
        '"name"\:"エクスポーション"' : '"name"\:"X-Potion"',
        '"name"\:"エクスマナポーション"' : '"name"\:"X-Mana Potion"',
        '"name"\:"瞬間裁縫セット"' : '"name"\:"Sewing Kit"',
        '"破れた衣服をすぐに元通りにできる"' : '"Repairs torn clothes."',
        '"完全回復薬　HPとMPともに全回復"' : '"Complete Recovery item\/Always useable.\\nCan be used in combat, fully recovers HP."',
//        '' : '',
// [Skills.json]
        '"の攻撃！"' : '" attacks!"',
        '"name"\:"攻撃"' : '"name"\:"Attack"',
        '"は身を守っている。"' : '" guards."',
        '"name"\:"防御"' : '"name"\:"Guard"',
        '"以下は、メニューを開いたとき、戦闘用のスキルより\\n上部に表示したいスキル用の枠です。"' : '"Below are spaces for when you would like to display \\nthings above skills when you open the menu."',
        '"name"\:"-----　予備"' : '"name"\:"-----　Spare"',
        '"以下は、主に敵が使用する前提のスキルです。\\n消費ＴＰが設定されていません。"' : '"Below are skills mainly for enemies to use. \\nTP cost is not set."',
        '"name"\:"-----　エネミー"' : '"name"\:"-----　Enemy"',
        '"敵単体に対して連続して攻撃を行う。"' : '"Performs a series of attacks on an enemy."',
        '"name"\:"連続攻撃"' : '"name"\:"Dual Attack"',
        '"ランダムな敵単体に対して２回攻撃を行う。"' : '"Performs a double attack on a random enemy."',
        '"name"\:"２回攻撃"' : '"name"\:"Double Attack"',
        '"ランダムな敵単体に対して３回攻撃を行う。"' : '"Performs a triple attack on a random enemy."',
        '"name"\:"３回攻撃"' : '"name"\:"Triple Attack"',
        '"使用者が戦闘から離脱します。"' : '"The user flees from battle."',
        '"は逃げてしまった。"' : '" flees."',
        '"name"\:"逃げる"' : '"name"\:"Escape"',
        '"ただ見てるだけ。"' : '"Just watching."',
        '"は様子を見ている。"' : '" waits."',
        '"name"\:"様子を見る"' : '"name"\:"Wait"',
        '"敵単体のＨＰを吸収する。"' : '"Absorbs HP from an enemy."',
        '"の吸血攻撃！"' : '" sucks blood!"',
        '"name"\:"吸血"' : '"name"\:"Blood Suck"',
        '"使用者のＨＰを回復する。"' : '"Recovers the user\'s HP."',
        '"は%1した！"' : '" %1s!"',
        '"name"\:"瞑想"' : '"name"\:"Meditate"',
        '"敵単体に毒針を刺し、麻痺状態にする。"' : '"Stabs an enemy with poison needles, paralyzing them."',
        '"は%1を放った！"' : '" does %1!"',
        '"name"\:"痺れ針"' : '"name"\:"Tranquilizer"',
        '"敵単体にダメージを与え、バランスを崩させる。"' : '"Inflicts damage and causes an enemy to lose balance."',
        '"は体当たりをした！"' : '" does bodyslam!"',
        '"name"\:"体当たり"' : '"name"\:"Bodyslam"',
        '"敵単体に雷属性のダメージを与え、麻痺させる。"' : '"Inflicts thunder-type damage and paralyzes an enemy."',
        '"name"\:"電撃"' : '"name"\:"Shock"',
        '"敵単体に粘液を付着させ、敏捷性を下げる。"' : '"Covers an enemy in slime and lowers their agility."',
        '"は粘液を吹きかけた！"' : '" shoots out slime!"',
        '"name"\:"粘液"' : '"name"\:"Slime"',
        '"敵単体に毒液を噴きかけ、毒状態にする。"' : '"Sprays an enemy with venom and poisons them."',
        '"name"\:"毒液"' : '"name"\:"Venom"',
        '"使用者の闘志を奮い立たたせ、能力を強化する。"' : '"Rouses the user\'s fighting spirit and fortifies \\ntheir abilities."',
        '"は、闘志をみなぎらせた！"' : '" rouses their fighting spirit!"',
        '"name"\:"咆哮"' : '"name"\:"Shout"',
        '"敵単体のＭＰを吸収する。"' : '"Absorbs MP from an enemy."',
        '"は奇妙なダンスを踊った！"' : '" dances bizarrely!"',
        '"name"\:"奇妙なダンス"' : '"name"\:"Bizarre Dance"',
        '"敵単体を睨みつけ、麻痺させる。"' : '"Glares at an enemy and paralyzes them."',
        '"name"\:"麻痺睨み"' : '"name"\:"Petrify"',
        '"敵単体を暗闇状態にする。"' : '"Blinds an enemy. "',
        '"name"\:"目潰し"' : '"name"\:"Eye Poke"',
        '"敵全体を暗闇状態にする。"' : '"Blinds all enemies."',
        '"name"\:"砂けむり"' : '"name"\:"Sandstorm"',
        '"name"\:"閃光"' : '"name"\:"Flash"',
        '"敵全体を毒状態にする。"' : '"Poisons all enemies."',
        '"name"\:"猛毒の霧"' : '"name"\:"Toxic Fog"',
        '"敵全体を睡眠状態にする。"' : '"Puts all enemies to sleep."',
        '"は%1を歌った！"' : '" sings a %1!"',
        '"name"\:"子守唄"' : '"name"\:"Lullaby"',
        '"敵全体を魅了する。"' : '"Fascinates all enemies."',
        '"name"\:"誘惑の歌"' : '"name"\:"Alluring Melody"',
        '"敵全体の魔法を封印する。"' : '"Seals all enemies\' magic."',
        '"name"\:"沈黙の歌"' : '"name"\:"Song of Silence"',
        '"敵全体を混乱状態にする。"' : '"Confuses all enemies."',
        '"name"\:"超音波"' : '"name"\:"Sonic Wave"',
        '"敵全体に大地属性のダメージを与える。"' : '"Inflicts ground-type damage on all enemies."',
        '"name"\:"石つぶて"' : '"name"\:"Throwing Stone"',
        '"敵全体に風属性のダメージを与える。"' : '"Inflicts wind-type damage on all enemies."',
        '"name"\:"鎌いたち"' : '"name"\:"Kamaitachi"',
        '"敵全体に炎属性のダメージを与える。"' : '"Inflicts fire-type damage on all enemies."',
        '"name"\:"ファイアブレス"' : '"name"\:"Fire Breath"',
        '"敵全体に氷属性のダメージを与える。"' : '"Inflicts ice-type damage on all enemies."',
        '"name"\:"アイスブレス"' : '"name"\:"Ice Breath"',
        '"敵全体に土属性のダメージを与える。"' : '"Inflicts earth-type damage on all enemies."',
        '"は%1をおこした！"' : '" causes an %1!"',
        '"name"\:"地震"' : '"name"\:"Earthquake"',
        '"敵全体に水属性のダメージを与える。"' : '"Inflicts water-type damage on all enemies."',
        '"name"\:"津波"' : '"name"\:"Tsunami"',
        '"name"\:"ひっかく"' : '"name"\:"Scratch"',
        '"以下は、主にプレイヤーが使用する前提の魔法スキルです。\\n敵が使用してもいいです。"' : '"Below are magic skills mainly for the player to use, \\nbut enemies may also use them."',
        '"name"\:"-----　基本の魔法"' : '"name"\:"-----　Basic Magic"',
        '"味方単体のＨＰを回復する。"' : '"Recovers an ally\'s HP."',
        '"は%1を唱えた！"' : '" casts %1!"',
        '"name"\:"ヒール"' : '"name"\:"Heal"',
        '"name"\:"ヒールⅠ"' : '"name"\:"Heal I"',
        '"name"\:"ヒールⅡ"' : '"name"\:"Heal II"',
        '"name"\:"ヒールⅢ"' : '"name"\:"Heal III"',
        '"味方全体のＨＰを回復する。"' : '"Recovers all allies\' HP."',
        '"name"\:"リカバー"' : '"name"\:"Recover"',
        '"name"\:"リカバーⅠ"' : '"name"\:"Recover I"',
        '"name"\:"リカバーⅡ"' : '"name"\:"Recover II"',
        '"name"\:"リカバーⅢ"' : '"name"\:"Recover III"',
        '"味方単体の毒・麻痺・睡眠を治療する。"' : '"Cures an ally\'s poisoned, paralyzed, or sleep state."',
        '"name"\:"キュアー"' : '"name"\:"Cure"',
        '"name"\:"キュアーⅠ"' : '"name"\:"Cure I"',
        '"味方単体の戦闘不能以外の状態異常を治療する。"' : '"Cures an ally\'s status ailments other than dead."',
        '"name"\:"キュアーⅡ"' : '"name"\:"Cure II"',
        '"味方全体の戦闘不能以外の状態異常を治療する。"' : '"Cures all allies\' status ailments other than dead."',
        '"name"\:"キュアーⅢ"' : '"name"\:"Cure III"',
        '"味方単体を戦闘不能から復活させる。"' : '"Raises an ally from the dead."',
        '"name"\:"レイズ"' : '"name"\:"Raise"',
        '"name"\:"レイズⅠ"' : '"name"\:"Raise I"',
        '"味方単体を戦闘不能から復活させ、ＨＰを大きく回復する。"' : '"Raises an ally from the dead and greatly recovers \\ntheir HP."',
        '"name"\:"レイズⅡ"' : '"name"\:"Raise II"',
        '"name"\:"ポイズン"' : '"name"\:"Poison"',
        '"name"\:"ブラインド"' : '"name"\:"Blind"',
        '"name"\:"コンフューズ"' : '"name"\:"Confuse"',
        '"name"\:"サイレンス"' : '"name"\:"Silence"',
        '"name"\:"スリープ"' : '"name"\:"Sleep"',
        '"敵全体を麻痺状態にする。"' : '"Paralyzes all enemies."',
        '"name"\:"パラライズ"' : '"name"\:"Paralyze"',
        '"味方単体の攻撃力を上げる。\\n２回まで重ねがけできる。"' : '"Increases an ally\'s attack. \\nUsable up to 2 times in a row."',
        '"name"\:"ウェポンブレス"' : '"name"\:"Weapon Breath"',
        '"敵全体の攻撃力を下げる。\\n２回まで重ねがけできる。"' : '"Decreases all enemies\' attacks. \\nUsable up to 2 times in a row."',
        '"name"\:"ウェポンカース"' : '"name"\:"Weapon Curse"',
        '"味方単体の防御力を上げる。\\n２回まで重ねがけできる。"' : '"Increases an ally\'s defense. \\nUsable up to 2 times in a row."',
        '"name"\:"アーマーブレス"' : '"name"\:"Armor Breath"',
        '"敵全体の防御力を下げる。\\n２回まで重ねがけできる。"' : '"Decreases all enemies\' defense. \\nUsable up to 2 times in a row."',
        '"name"\:"アーマーカース"' : '"name"\:"Armor Curse"',
        '"味方単体の魔法力を上げる。\\n２回まで重ねがけできる。"' : '"Increases an ally\'s M.Attack. \\nUsable up to 2 times in a row."',
        '"name"\:"スピリットブレス"' : '"name"\:"Spirit Breath"',
        '"敵全体の魔法力を下げる。\\n２回まで重ねがけできる。"' : '"Decreases all enemies\' M.Attack. \\nUsable up to 2 times in a row."',
        '"name"\:"スピリットカース"' : '"name"\:"Spirit Curse"',
        '"味方単体の魔法防御力を上げる。\\n２回まで重ねがけできる。"' : '"Increases an ally\'s M.Defense. \\nUsable up to 2 times in a row."',
        '"name"\:"ディバインブレス"' : '"name"\:"Divine Breath"',
        '"敵全体の魔法防御力を下げる。\\n２回まで重ねがけできる。"' : '"Decreases all enemies\' M.Defense. \\nUsable up to 2 times in a row."',
        '"name"\:"ディバインカース"' : '"name"\:"Divine Curse"',
        '"味方単体の敏捷を上げる。\\n２回まで重ねがけできる。"' : '"Increases an ally\'s agility. \\nUsable up to 2 times in a row."',
        '"name"\:"クイックムーブ"' : '"name"\:"Quicken Movement"',
        '"敵全体の敏捷を下げる。\\n２回まで重ねがけできる。"' : '"Decreases all enemies\' agility. \\nUsable up to 2 times in a row."',
        '"name"\:"スロームーブ"' : '"name"\:"Slow Movement"',
        '"name"\:"ライフドレイン"' : '"name"\:"Life Drain"',
        '"name"\:"マナドレイン"' : '"name"\:"Mana Drain"',
        '"敵単体に炎属性のダメージを与える。"' : '"Inflicts fire-type damage on an enemy."',
        '"name"\:"ファイア"' : '"name"\:"Fire"',
       '"name"\:"ファイアⅠ"' : '"name"\:"Fire I"',
        '"name"\:"ファイアⅡ"' : '"name"\:"Fire II"',
        '"name"\:"ファイアⅢ"' : '"name"\:"Fire III"',
        '"name"\:"フレイムⅠ"' : '"name"\:"Flame I"',
        '"name"\:"フレイムⅡ"' : '"name"\:"Flame II"',
        '"name"\:"フレイムⅢ"' : '"name"\:"Flame III"',
        '"敵単体に氷属性のダメージを与える。"' : '"Inflicts ice-type damage on an enemy."',
        '"name"\:"アイス"' : '"name"\:"Ice"',
        '"name"\:"アイスⅠ"' : '"name"\:"Ice I"',
        '"name"\:"アイスⅡ"' : '"name"\:"Ice II"',
        '"name"\:"アイスⅢ"' : '"name"\:"Ice III"',
        '"name"\:"ブリザード"' : '"name"\:"Blizzard"',
        '"name"\:"ブリザードⅠ"' : '"name"\:"Blizzard I"',
        '"name"\:"ブリザードⅡ"' : '"name"\:"Blizzard II"',
        '"name"\:"ブリザードⅢ"' : '"name"\:"Blizzard III"',
        '"敵単体に雷属性のダメージを与える。"' : '"Inflicts thunder-type damage on an enemy."',
        '"name"\:"サンダー"' : '"name"\:"Thunder"',
        '"name"\:"サンダーⅠ"' : '"name"\:"Thunder I"',
        '"name"\:"サンダーⅡ"' : '"name"\:"Thunder II"',
        '"name"\:"サンダーⅢ"' : '"name"\:"Thunder III"',
        '"敵全体に雷属性のダメージを与える。"' : '"Inflicts thunder-type damage on all enemies."',
        '"name"\:"スパーク"' : '"name"\:"Spark"',
        '"name"\:"スパークⅠ"' : '"name"\:"Spark I"',
        '"name"\:"スパークⅡ"' : '"name"\:"Spark II"',
        '"name"\:"スパークⅢ"' : '"name"\:"Spark III"',
        '"敵単体に水属性のダメージを与える。"' : '"Inflicts water-type damage on an enemy."',
        '"name"\:"ウォーター"' : '"name"\:"Water"',
        '"name"\:"ウォーターⅠ"' : '"name"\:"Water I"',
        '"name"\:"ウォーターⅡ"' : '"name"\:"Water II"',
        '"name"\:"ウェーブⅠ"' : '"name"\:"Wave I"',
        '"name"\:"ウェーブⅡ"' : '"name"\:"Wave II"',
        '"敵単体に大地属性のダメージを与える。"' : '"Inflicts ground-type damage on an enemy."',
        '"name"\:"ストーン"' : '"name"\:"Stone"',
        '"name"\:"ストーンⅠ"' : '"name"\:"Stone I"',
        '"name"\:"ストーンⅡ"' : '"name"\:"Stone II"',
        '"name"\:"クェイク"' : '"name"\:"Quake"',
        '"name"\:"クェイクⅠ"' : '"name"\:"Quake I"',
        '"name"\:"クェイクⅡ"' : '"name"\:"Quake II"',
        '"敵単体に風属性のダメージを与える。"' : '"Inflicts wind-type damage on an enemy."',
        '"name"\:"ウインド"' : '"name"\:"Wind"',
        '"name"\:"ウインドⅠ"' : '"name"\:"Wind I"',
        '"name"\:"ウインドⅡ"' : '"name"\:"Wind II"',
        '"name"\:"トルネード"' : '"name"\:"Tornado"',
        '"name"\:"トルネードⅠ"' : '"name"\:"Tornado I"',
        '"name"\:"トルネードⅡ"' : '"name"\:"Tornado II"',
        '"敵単体に神聖属性のダメージを与える。"' : '"Inflicts divine-type damage on an enemy."',
        '"name"\:"セイント"' : '"name"\:"Saint"',
        '"name"\:"セイントⅠ"' : '"name"\:"Saint I"',
        '"name"\:"セイントⅡ"' : '"name"\:"Saint II"',
        '"敵全体に神聖属性のダメージを与える。"' : '"Inflicts divine-type damage on all enemies."',
        '"name"\:"スターライト"' : '"name"\:"Starlight"',
        '"name"\:"スターライトⅠ"' : '"name"\:"Starlight I"',
        '"name"\:"スターライトⅡ"' : '"name"\:"Starlight II"',
        '"敵単体に暗黒属性のダメージを与える。"' : '"Inflicts dark-type damage on an enemy."',
        '"name"\:"シェイド"' : '"name"\:"Shade"',
        '"name"\:"シェイドⅠ"' : '"name"\:"Shade I"',
        '"name"\:"シェイドⅡ"' : '"name"\:"Shade II"',
        '"敵全体に暗黒属性のダメージを与える。"' : '"Inflicts dark-type damage on all enemies."',
        '"name"\:"ダークネス"' : '"name"\:"Darkness"',
        '"name"\:"ダークネスⅠ"' : '"name"\:"Darkness I"',
        '"name"\:"ダークネスⅡ"' : '"name"\:"Darkness II"',
        '"敵単体に防御無視のダメージを与える。"' : '"Inflicts damage on an enemy regardless of defense."',
        '"name"\:"バースト"' : '"name"\:"Burst"',
        '"name"\:"バーストⅠ"' : '"name"\:"Burst I"',
        '"name"\:"バーストⅡ"' : '"name"\:"Burst II"',
        '"敵全体に防御無視のダメージを与える。"' : '"Inflicts damage on all enemies regardless of defense."',
        '"name"\:"ニュークリア"' : '"name"\:"Nuke"',
        '"name"\:"ニュークリアⅠ"' : '"name"\:"Nuke I"',
        '"name"\:"ニュークリアⅡ"' : '"name"\:"Nuke II"',
        '"以下は、主に剣士が使用する前提のスキルです。"' : '"Below are skills mainly for swordsmen to use."',
        '"name"\:"-----　剣士・戦士系スキル"' : '"name"\:"-----　Swordsman & Warrior Skills"',
        '"敵単体に対して強力な攻撃を行う。"' : '"Performs a powerful attack on an enemy."',
        '"name"\:"強撃"' : '"name"\:"Strong Attack"',
        '"敵全体に対して攻撃を行う。"' : '"Attacks all enemies."',
        '"は薙ぎ払った！"' : '" mows down the enemy!"',
        '"name"\:"薙ぎ払い"' : '"name"\:"Slash"',
        '"敵単体に対して２回攻撃を行う。"' : '"Performs an attack on an enemy twice."',
        '"の連続攻撃！"' : '" dual attacks!"',
        '"使用者の闘志を奮い立たたせ、攻撃力を上げる。\\n２回まで重ねがけできる。"' : '"Rouses the user\'s fighting spirit and increases \\nattack. Usable up to 2 times in a row."',
        '"は%1を入れた！"' : '" uses %1!"',
        '"name"\:"気合い"' : '"name"\:"Willpower"',
        '"は%1を行った！"' : '" performs %1!"',
        '"name"\:"応急処置"' : '"name"\:"First Aid"',
        '"敵単体に対して超強力な攻撃を行う。"' : '"Performs a super powerful attack on an enemy."',
        '"name"\:"乙女の構え"' : '"name"\:"Maiden\'s Stance"',
        '"敵全体に対して強攻撃を行う。"' : '"Performs a powerful attack on all enemies."',
        '"name"\:"スピンクラッシュ"' : '"name"\:"Spin Crash"',
        '"以下は、主に魔法使いが使用する前提のスキルです。"' : '"Below are skills mainly for sorcerers to use."',
        '"name"\:"-----　僧侶・魔法使い系スキル"' : '"name"\:"-----　Priest & Sorcerer Skills"',
        '"味方全体の防御力・魔法防御力を上げる。\\n２回まで重ねがけできる。"' : '"Increases all allies\' defense and M.Defense. \\nUsable up to 2 times in a row."',
        '"は祈りを捧げた！"' : '" offered prayer!"',
        '"name"\:"マジックバリア"' : '"name"\:"Magic Barrier"',
        '"５ターンの間、使用者の魔法力を大幅に上げる。"' : '"Greatly increases the user\'s M.Attack for 5 turns."',
        '"name"\:"スペルエンハンス"' : '"name"\:"Spell Enhancement"',
        '"味方全体の闘志を奮い立たたせ、攻撃力を上げる。\\n２回まで重ねがけできる。"' : '"Rouses all allies\' fighting spirit and increases \\nattack. Usable up to 2 times in a row."',
        '"は応援した！"' : '" gave encouragement!"',
        '"name"\:"エール"' : '"name"\:"Yell"',
        '"name"\:"メテオ"' : '"name"\:"Meteor"',
        '"５ターンの間、炎属性を付与する。"' : '"Bestows fire attributes for 5 turns."',
        '"name"\:"ファイアウエポン"' : '"name"\:"Fire Weapon"',
        '"５ターンの間、氷属性を付与する。"' : '"Bestows ice attributes for 5 turns."',
        '"name"\:"アイスウエポン"' : '"name"\:"Ice Weapon"',
        '"５ターンの間、雷属性を付与する。"' : '"Bestows thunder attributes for 5 turns."',
        '"name"\:"サンダーウエポン"' : '"name"\:"Thunder Weapon"',
        '"５ターンの間、使用者に向けられた攻撃魔法を反射する。"' : '"Reflects magic attacks aimed at the user for 5 turns."',
        '"name"\:"マジックミラー"' : '"name"\:"Magic Mirror"',
        '"以下は、主に騎士が使用する前提のスキルです。\\n（武器は、槍がメイン）"' : '"Below are skills mainly for knights to use. \\n(Weapons are mostly spears.)"',
        '"name"\:"-----　騎士系スキル"' : '"name"\:"-----　Knight Skills"',
        '"１ターンの間、ＨＰの少ない味方を自動的にかばう。"' : '"Automatically protects allies with low HP for 1 turn."',
        '"は仲間をかばっている。"' : '" protects team."',
        '"name"\:"かばう"' : '"name"\:"Protect"',
        '"誰よりも早く敵単体に攻撃を行なう。"' : '"Performs an attack on an enemy faster than anyone \\nelse."',
        '"name"\:"隼突き"' : '"name"\:"Falcon Thrust"',
        '"name"\:"二段突き"' : '"name"\:"Double Thrust"',
        '"敵単体に防御力無視の攻撃を行なう。"' : '"Inflicts damage on all enemies regardless of defense."',
        '"name"\:"鎧通し"' : '"name"\:"Armor Piercer"',
        '"は一喝した！"' : '" made a battle cry!"',
        '"name"\:"一喝"' : '"name"\:"Battle Cry"',
        '"name"\:"風車"' : '"name"\:"Windmill"',
        '"使用者のＴＰを少し増やす。"' : '"Slightly increases the user\'s TP."',
        '"は心を無にした！"' : '" cleared their mind!"',
        '"name"\:"心頭滅却"' : '"name"\:"Clear Mind"',
        '"敵４体に対してランダムに４回攻撃を行う。"' : '"Randomly performs 4 attacks on 4 enemies."',
        '"name"\:"乱れ突き"' : '"name"\:"Wild Thrust"',
        '"以下は、主に盗賊が使用する前提のスキルです。"' : '"Below are skills mainly for bandits to use."',
        '"name"\:"-----　盗賊系スキル"' : '"name"\:"-----　Bandit Skills"',
        '"使用者の敏捷を上げる。\\n"' : '"Increases the user\'s agility.\\n"',
        '"は%1を始めた！"' : '" started %1!"',
        '"name"\:"準備運動"' : '"name"\:"Warm-up"',
        '"name"\:"閃光弾"' : '"name"\:"Flare"',
        '"アイテムのドロップ率を上げる。"' : '"Increases items and money gained from battle for \\na while."',
        '"は隙をうかがっている。"' : '" observes the surroundings carefully."',
        '"name"\:"隙をうかがう"' : '"name"\:"Watchful Eye"',
        '"敵全体にダメージを与える。"' : '"Inflicts huge damage on all enemies."',
        '"標的になりにくくする。"' : '"Makes the user harder to target."',
        '"name"\:"隠れる"' : '"name"\:"Hide"',
        '"以下は、主に格闘家が使用する前提のスキルです。"' : '"Below are skills mainly for martial artists to use."',
        '"name"\:"-----　格闘家系スキル"' : '"name"\:"-----　Martial Artist Skills"',
        '"敵全体にダメージを与え、バランスを崩させる。"' : '"Inflicts damage and causes all enemies to lose balance."',
        '"name"\:"足払い"' : '"name"\:"Sweep"',
        '"使用者の弱体化を治療する。"' : '"Cures the user from being weakened."',
        '"は%1を使った！"' : '" uses %1!"',
        '"name"\:"気孔術"' : '"name"\:"Qigong "',
        '"敵全体に強力なダメージを与える。"' : '"Inflicts huge damage on all enemies. "',
        '"name"\:"回し蹴り"' : '"name"\:"Roundhouse Kick"',
        '"敵単体に防御無視の強力なダメージを与える。"' : '"Inflicts damage on an enemy regardless of defense."',
        '"name"\:"猛虎乱舞"' : '"name"\:"Tiger Dance"',
        '"以下は、主に狩人が使用する前提のスキルです。"' : '"Below are skills mainly for hunters to use."',
        '"name"\:"-----　狩人系スキル"' : '"name"\:"-----　Hunter Skills"',
        '"敵単体の攻撃力と防御力を下げる。"' : '"Decreases an enemy\'s attack and defense."',
        '"name"\:"ポイントショット"' : '"name"\:"Point Shot"',
        '"敵全体の足元を打ち抜き、バランスを崩させる。"' : '"Shoots at all enemy\'s footing and causes them to \\nlose balance."',
        '"name"\:"スタンショット"' : '"name"\:"Stun Shot"',
        '"敵単体に5回ダメージを与える。"' : '"Inflicts damage on an enemy 5 times."',
        '"name"\:"チームショット"' : '"name"\:"Team Shot"',
        '"敵全体に２回ダメージを与える。"' : '"Inflicts damage on all enemies 2 times."',
        '"name"\:"レインショット"' : '"name"\:"Rain Shot"',
// non-original
        '"name"\:"トランス"' : '"name"\:"Trans"',
        '"name"\:"コンセントレイト"' : '"name"\:"Concentration"',
        '"name"\:"回復"' : '"name"\:"Recovery"',
        '"name"\:"サポート"' : '"name"\:"Support"',
        '"name"\:"ファイヤ"' : '"name"\:"Fire"',
        '"name"\:"ドレイン"' : '"name"\:"Drain"',
        '"name"\:"連撃"' : '"name"\:"Multi-shot"',
        '"name"\:"ダーク"' : '"name"\:"Dark"',
        //'' : '',
// [States.json]
        '"は倒れた！"' : '" has fallen!"',
        '"を倒した！"' : '" is slain!"',
        '"は立ち上がった！"' : '" revives!"',
        '"name"\:"戦闘不能"' : '"name"\:"Dead"',
        '"name"\:"不死身"' : '"name"\:"Immortal"',
        '"は毒にかかった！"' : '" was poisoned!"',
        '"に毒をかけた！"' : '" is poisoned!"',
        '"の毒が消えた！"' : '" is no longer poisoned!"',
        '"name"\:"毒"' : '"name"\:"Poison"',
        '"は暗闇に閉ざされた！"' : '" was blinded!"',
        '"を暗闇に閉ざした！"' : '" is blinded!"',
        '"の暗闇が消えた！"' : '" is no longer blinded!"',
        '"name"\:"暗闇"' : '"name"\:"Blind"',
        '"は沈黙した！"' : '" was silenced!"',
        '"を沈黙させた！"' : '" is silenced!"',
        '"の沈黙が解けた！"' : '" is no longer silenced!"',
        '"name"\:"沈黙"' : '"name"\:"Silence"',
        '"は激昂した！"' : '" was enraged!"',
        '"を激昂させた！"' : '" is enraged!"',
        '"name"\:"激昂"' : '"name"\:"Rage"',
        '"は混乱した！"' : '" was confused!"',
        '"を混乱させた！"' : '" is confused!"',
        '"name"\:"混乱"' : '"name"\:"Confusion"',
        '"は魅了された！"' : '" was fascinated!"',
        '"を魅了した！"' : '" is fascinated!"',
        '"name"\:"魅了"' : '"name"\:"Fascination"',
        '"は眠った！"' : '" falls asleep!"',
        '"を眠らせた！"' : '" still sleeping!"',
        '"は眠っている。"' : '" is still sleeping..."',
        '"は目を覚ました！"' : '" wakes up!"',
        '"name"\:"睡眠"' : '"name"\:"Sleep"',
        '"はしびれて動けなくなった！"' : '" was paralyzed and can\'t move!"',
        '"を麻痺させた！"' : '" is paralyzed!"',
        '"は体がしびれて動けない！"' : '" is paralyzed and can\'t move!"',
        '"の麻痺が解けた！"' : '" is no longer paralyzed!"',
        '"name"\:"麻痺"' : '"name"\:"Paralyze"',
        '"はバランスを崩した！"' : '" lost balance!"',
        '"はバランスを崩している……"' : '" is still off-balance..."',
        '"は体勢を立て直した！"' : '" regained balance!"',
        '"name"\:"スタン"' : '"name"\:"Stun"',
        '"name"\:"HP再生"' : '"name"\:"HP Regeneration"',
        '"name"\:"MP再生"' : '"name"\:"MP Regeneration"',
        '"name"\:"TP再生"' : '"name"\:"TP Regeneration"',
        '"name"\:"魔法反射"' : '"name"\:"Magic Reflection"',
        '"は狙われやすくなった！"' : '" became easier to hit!"',
        '"name"\:"挑発"' : '"name"\:"Provoke"',
        '"は狙われにくくなった！"' : '" became harder to hit!"',
        '"name"\:"反撃"' : '"name"\:"Counter Attack"',
        '"name"\:"状態異常防止"' : '"name"\:"Status Ailment Block"',
        '"name"\:"消費MP減"' : '"name"\:"Reduce MP Cost"',
        '"は炎の力を身にまとった。"' : '" is shrouded in the force of fire."',
        '"name"\:"炎の力"' : '"name"\:"Fire Force"',
        '"は氷の力を身にまとった。"' : '" is shrouded in the force of ice."',
        '"name"\:"氷の力"' : '"name"\:"Ice Force"',
        '"は雷の力を身にまとった。"' : '" is shrouded in the force of thunder."',
        '"name"\:"雷の力"' : '"name"\:"Thunder Force"',
        '"name"\:"エンカウント半減"' : '"name"\:"Encounter Half"',
        '"name"\:"賞金・アイテム2倍"' : '"name"\:"Double Money/Items"',
// other original
        '"は我に返った！"' : '" has come to senses!"',
//        '"name"\:"???"' : '"name"\:"Knockout"
//        '"???"' : '" is no longer confused!"
//        '"???"' : '" is no longer fascinated!"
// non-original
        '"は麻痺して動けなくなった！"' : '" can\'t move!"',
        '"を麻痺で動けなくさせた！"' : '" can\'t move!"',
        '"は痺れていて動けない。"' : '" is still paralyzed!"',
        '"は麻痺から回復した！"' : '" can move again!"',
        //'' : '',
// [System.json]
// armorTypes
        '"一般防具"' : '"General Armor"',
        '"魔法防具"' : '"Magic Armor"',
        '"軽装防具"' : '"Light Armor"',
        '"重装防具"' : '"Heavy Armor"',
        '"小型盾"' : '"Small Shield"',
        '"大型盾"' : '"Large Shield"',
// non-original
        '"アクセサリ"' : '"Accessory"',
//        '' : '',
// elements
        '"物理"' : '"Physical"',
        '"炎"' : '"Fire"',
        '"氷"' : '"Ice"',
        '"雷"' : '"Thunder"',
        '"水"' : '"Water"',
        '"土"' : '"Earth"',
        '"風"' : '"Wind"',
        '"光"' : '"Light"',
        '"闇"' : '"Darkness"',
// equipTypes
        '"武器"' : '"Weapon"',
        '"盾"' : '"Shield"',
        '"頭"' : '"Head"',
        '"身体"' : '"Body"',
// non-original
        '"装飾品"' : '"Accessory"',
// skillTypes
// non-original
        '"魔法"' : '"Magic"',
        '"戦技"' : '"Skills"',
        '"パッシヴスキル"' : '"Passive skill"',
        '"バトルスキル"' : '"Battle skill"',
        '"マジックスキル"' : '"Magic skill"',
// terms : basic
        '"レベル"' : '"Level"',
        '"ＨＰ"' : '"HP"',
        '"ＭＰ"' : '"MP"',
        '"ＴＰ"' : '"TP"',
        '"経験値"' : '"Experience"',
// commands
        '"戦う"' : '"Fight"',
        '"逃げる"' : '"Escape"',
        '"攻撃"' : '"Attack"',
        '"防御"' : '"Guard"',
        '"アイテム"' : '"Item"',
        '"スキル"' : '"Skill"',
        '"装備"' : '"Equip"',
        '"ステータス"' : '"Status"',
        '"並び替え"' : '"Formation"',
        '"セーブ"' : '"Save"',
        '"ゲーム終了"' : '"Quit Game"',
        '"オプション"' : '"Options"',
        '"防具"' : '"Armor"',
        '"大事なもの"' : '"Key Items"',
        '"最強装備"' : '"Optimize"',
        '"全て外す"' : '"Clear"',
        '"ニューゲーム"' : '"New Game"',
        '"コンティニュー"' : '"Continue"',
        '"タイトルへ"' : '"Title"',
        '"やめる"' : '"Cancel"',
        '"購入する"' : '"Buy"',
        '"売却する"' : '"Sell"',
// params
        '"最大ＨＰ"' : '"Max HP"',
        '"最大ＭＰ"' : '"Max MP"',
        '"防御力"' : '"Defense"',
        '"魔力"' : '"M.Attack"',
        '"魔法防御"' : '"M.Defense"',
        '"敏捷性"' : '"Agility"',
        '"運"' : '"Luck"',
        '"命中率"' : '"Hit"',
// non-original
        '"攻撃力"' : '"Attack"',
        '"魔法力"' : '"Magic"',
        '"回避率"' : '"Evasion"',
        '"すばやさ"' : '"Speed"',
// messages
	// Skill and Item Failure
        '"actionFailure"\:"%1には効かなかった！"' : '"actionFailure"\:"There was no effect on %1!"',
	// Results for Actions on Actors
        '"actorDamage"\:"%1は %2 のダメージを受けた！"' : '"actorDamage"\:"%1 took %2 damage!"',
        '"actorDrain"\:"%1は%2を %3 奪われた！"' : '"actorDrain"\:"%1 was drained of %2 %3!"',
        '"actorGain"\:"%1の%2が %3 増えた！"' : '"actorGain"\:"%1 gained %2 %3!"',
        '"actorLoss"\:"%1の%2が %3 減った！"' : '"actorLoss"\:"%1 lost %2 %3!"',
        '"actorNoDamage"\:"%1はダメージを受けていない！"' : '"actorNoDamage"\:"%1 took no damage!"',
        '"actorNoHit"\:"ミス！　%1はダメージを受けていない！"' : '"actorNoHit"\:"Miss! %1 took no damage!"',
        '"actorRecovery"\:"%1の%2が %3 回復した！"' : '"actorRecovery"\:"%1 recovered %2 %3!"',
	// Other
        '"alwaysDash"\:"常時ダッシュ"' : '"alwaysDash"\:"Always Dash"',
	// Volume Options
        '"bgmVolume"\:"BGM 音量"' : '"bgmVolume"\:"BGM Volume"',
        '"bgsVolume"\:"BGS 音量"' : '"bgsVolume"\:"BGS Volume"',
	// Status Increase/Decrease
        '"buffAdd"\:"%1の%2が上がった！"' : '"buffAdd"\:"%1\'s %2 went up!"',
        '"buffRemove"\:"%1の%2が元に戻った！"' : '"buffRemove"\:"%1\'s %2 returned to normal!"',
	// Other
        '"commandRemember"\:"コマンド記憶"' : '"commandRemember"\:"Command Remember"',
	// Evasion/Reflection
        '"counterAttack"\:"%1の反撃！"' : '"counterAttack"\:"%1 counterattacked!"',
	// Critical Hit
        '"criticalToActor"\:"痛恨の一撃！！"' : '"criticalToActor"\:"A painful blow!!"',
        '"criticalToEnemy"\:"会心の一撃！！"' : '"criticalToEnemy"\:"An excellent hit!!"',
	// Status Increase/Decrease
        '"debuffAdd"\:"%1の%2が下がった！"' : '"debuffAdd"\:"%1\'s %2 went down!"',
	// Battle Ending Messages
        '"defeat"\:"%1は戦いに敗れた。"' : '"defeat"\:"%1 was defeated."',
	// Basic Battle Messages
        '"emerge"\:"%1が出現！"' : '"emerge"\:"%1 emerged!"',
	// Results for Actions on Enemy
        '"enemyDamage"\:"%1に %2 のダメージを与えた！"' : '"enemyDamage"\:"%1 took %2 damage!"',
        '"enemyDrain"\:"%1の%2を %3 奪った！"' : '"enemyDrain"\:"%1 was drained of %2 %3!"',
        '"enemyGain"\:"%1の%2が %3 増えた！"' : '"enemyGain"\:"%1 gained %2 %3!"',
        '"enemyLoss"\:"%1の%2が %3 減った！"' : '"enemyLoss"\:"%1 lost %2 %3!"',
	// Results for Actions on Enemy
        '"enemyNoDamage"\:"%1にダメージを与えられない！"' : '"enemyNoDamage"\:"%1 took no damage!"',
        '"enemyNoHit"\:"ミス！　%1にダメージを与えられない！"' : '"enemyNoHit"\:"Miss! %1 took no damage!"',
        '"enemyRecovery"\:"%1の%2が %3 回復した！"' : '"enemyRecovery"\:"%1 recovered %2 %3!"',
	// Basic Battle Messages
        '"escapeFailure"\:"しかし逃げることはできなかった！"' : '"escapeFailure"\:"However, it was unable to escape!"',
        '"escapeStart"\:"%1は逃げ出した！"' : '"escapeStart"\:"%1 has started to escape!"',
	// Evasion/Reflection
        '"evasion"\:"%1は攻撃をかわした！"' : '"evasion"\:"%1 evaded the attack!"',
	// Status Screen
        '"expNext"\:"次の%1まで"' : '"expNext"\:"To next %1"',
        '"expTotal"\:"現在の%1"' : '"expTotal"\:"Current %1"',
	// Save/Load Screen
        '"file"\:"ファイル"' : '"file"\:"File"',
	// Battle Ending Messages
        '"levelUp"\:"%1は%2 %3 に上がった！"' : '"levelUp"\:"%1 is now %2 %3!"',
	// Save/Load Screen
        '"loadMessage"\:"どのファイルをロードしますか？"' : '"loadMessage"\:"Load which file?"',
	// Evasion/Reflection
        '"magicEvasion"\:"%1は魔法を打ち消した！"' : '"magicEvasion"\:"%1 nullified the magic!"',
        '"magicReflection"\:"%1は魔法を跳ね返した！"' : '"magicReflection"\:"%1 reflected the magic!"',
	// Volume Options
        '"meVolume"\:"ME 音量"' : '"meVolume"\:"ME Volume"',
	// Battle Ending Messages
        '"obtainExp"\:"%1 の%2を獲得！"' : '"obtainExp"\:"%1 %2 received!"',
        '"obtainGold"\:"お金を %1\\\\G 手に入れた！"' : '"obtainGold"\:"%1\\\\G found!"',
        '"obtainItem"\:"%1を手に入れた！"' : '"obtainItem"\:"%1 found!"',
        '"obtainSkill"\:"%1を覚えた！"' : '"obtainSkill"\:"%1 learned!"',
	// Display when there are multiple members
        '"partyName"\:"%1たち"' : '"partyName"\:"%1\'s Party"',
	// Shop Screen
        '"possession"\:"持っている数"' : '"possession"\:"Possession"',
	// Basic Battle Messages
        '"preemptive"\:"%1は先手を取った！"' : '"preemptive"\:"%1 got the upper hand!"',
	// Save/Load Screen
        '"saveMessage"\:"どのファイルにセーブしますか？"' : '"saveMessage"\:"Save to which file?"',
	// Volume Options
        '"seVolume"\:"SE 音量"' : '"seVolume"\:"SE Volume"',
	// Evasion/Reflection
        '"substitute"\:"%1が%2をかばった！"' : '"substitute"\:"%1 protected %2!"',
	// Basic Battle Messages
        '"surprise"\:"%1は不意をつかれた！"' : '"surprise"\:"%1 was surprised!"',
	// Item Use
        '"useItem"\:"%1は%2を使った！"' : '"useItem"\:"%1 uses %2!"',
	// Battle Ending Messages
        '"victory"\:"%1の勝利！"' : '"victory"\:"%1 was victorious!"',
// weaponTypes
        '"短剣"' : '"Dagger"',
        '"剣"' : '"Sword"',
        '"フレイル"' : '"Flail"',
        '"斧"' : '"Axe"',
        '"ムチ"' : '"Whip"',
        '"杖"' : '"Cane"',
        '"弓"' : '"Bow"',
        '"クロスボウ"' : '"Crossbow"',
        '"銃"' : '"Gun"',
        '"爪"' : '"Claw"',
        '"グローブ"' : '"Glove"',
        '"槍"' : '"Spear"',
// non-original
//other
        '"はい"' : '"Yes"',
        '"いいえ"' : '"No"',
        '"キャンセル"' : '"Cancel"',
        '"なし"' : '"None"',
         '"currencyUnit"\:"Ｇ"' : '"currencyUnit"\:"G"',
         '"currencyUnit"\:"円"' : '"currencyUnit"\:"Yen"',
//       '' : '',
// [Troops.json]
        '"name"\:"スライム\\*2"' : '"name"\:"Slime\*2"',
        '"name"\:"ホーネット\\*2"' : '"name"\:"Hornet\*2"',
        '"name"\:"ホーネット\\*2　プラント"' : '"name"\:"Hornet\*2　Demon Plant"',
        '"name"\:"プラント\\*2"' : '"name"\:"Demon Plant\*2"',
        '"name"\:"キラーラット\\*3"' : '"name"\:"Killer Rat\*3"',
        '"name"\:"バット\\*2"' : '"name"\:"Bat\*2"',
        '"name"\:"スパイダー\\*3"' : '"name"\:"Spider\*3"',
        '"name"\:"スネイク\\*2"' : '"name"\:"Snake\*2"',
        '"name"\:"バット\\*2　スネイク"' : '"name"\:"Bat\*2　Snake"',
        '"name"\:"インプ\\*3"' : '"name"\:"Imp\*3"',
        '"name"\:"バット\\*2　インプ"' : '"name"\:"Bat\*2　Imp"',
        '"name"\:"盗賊\\*3"' : '"name"\:"Bandit\*3"',
        '"name"\:"オーク\\*2"' : '"name"\:"Orc\*2"',
// non-original
        '"name"\:"こうもり\\*2"' : '"name"\:"Bat\*2"',
        '"name"\:"こうもり\\*3"' : '"name"\:"Bat\*3"',
        '"name"\:"ミノタウロス\\*2"' : '"name"\:"Minotaur\*2"',
        '"name"\:"ミノタウロス\\*3"' : '"name"\:"Minotaur\*3"',
        '"name"\:"エキドナ\\*2"' : '"name"\:"Echidna\*2"',
        '"name"\:"エキドナ\\*3"' : '"name"\:"Echidna\*3"',
        '"name"\:"ハーピー\\*2"' : '"name"\:"Harpy\*2"',
        '"name"\:"ハーピー\\*3"' : '"name"\:"Harpy\*3"',
// [Weapons.json]
        '"【剣】軽くて扱いやすい刀身の短い剣。"' : '"\[Sword\] A light and easy-to-wield short-bladed sword."',
        '"軽くて扱いやすい刀身の短い剣。"' : '"A light and easy-to-wield short-bladed sword."',
        '"name"\:"ショートソード"' : '"name"\:"Short Sword"',
        '"【剣】鋭い切れ味を誇る戦闘用の長剣。"' : '"\[Sword\] A long battle sword boasting a sharp cut."',
        '"鋭い切れ味を誇る戦闘用の長剣。"' : '"A long battle sword boasting a sharp cut."',
        '"name"\:"ロングソード"' : '"name"\:"Long Sword"',
        '"【剣】反りのある刀身をもつ幅広の剣。"' : '"\[Sword\] A wide sword with a curved blade."',
        '"反りのある刀身をもつ幅広の剣。"' : '"A wide sword with a curved blade."',
        '"name"\:"ファルシオン"' : '"name"\:"Falchion"',
        '"【剣】ミスリルで作られた長剣。"' : '"\[Sword\] A long sword forged of mithril."',
        '"ミスリルで作られた長剣。"' : '"A long sword forged of mithril."',
        '"name"\:"ミスリルソード"' : '"name"\:"Mithril Sword"',
        '"【剣】ドラゴンのキバで作られた剣。"' : '"\[Sword\] A sword forged of dragon\'s fangs. "',
        '"ドラゴンのキバで作られた剣。"' : '"A sword forged of dragon\'s fangs. "',
        '"name"\:"ドラゴンブレード"' : '"name"\:"Dragon Blade"',
        '"【杖】安価で一般に普及している杖。"' : '"\[Staff\] An inexpensive and widely-used staff."',
        '"安価で一般に普及している杖。"' : '"An inexpensive and widely-used staff."',
        '"name"\:"ウッドスタッフ"' : '"name"\:"Wooden Staff"',
        '"【杖】術者の魔力をやや増幅させる杖。"' : '"\[Staff\] A wand that slightly increases its wielder\'s \\nmagical powers. "',
        '"術者の魔力をやや増幅させる杖。"' : '"A wand that slightly increases its wielder\'s \\nmagical powers. "',
        '"name"\:"マジックワンド"' : '"name"\:"Magic Wand"',
        '"【杖】術者の魔力を増幅させる銀製の杖。"' : '"\[Staff\] A silver wand that increases its wielder\'s \\nmagical powers."',
        '"術者の魔力を増幅させる銀製の杖。"' : '"A silver wand that increases its wielder\'s \\nmagical powers."',
        '"name"\:"フォースワンド"' : '"name"\:"Force Wand"',
        '"【杖】術者の魔力を増幅させるミスリルの杖。"' : '"\[Staff\] A mithril rod that increases its wielder\'s \\nmagical powers."',
        '"術者の魔力を増幅させるミスリルの杖。"' : '"A mithril rod that increases its wielder\'s \\nmagical powers."',
        '"name"\:"ミスリルロッド"' : '"name"\:"Mithril Rod"',
        '"【杖】術者の魔力を増幅させるドラゴンの杖。"' : '"\[Staff\] A dragon staff that increases its wielder\'s \\nmagical powers."',
        '"術者の魔力を増幅させるドラゴンの杖。"' : '"A dragon staff that increases its wielder\'s \\nmagical powers."',
        '"name"\:"ドラゴンスタッフ"' : '"name"\:"Dragon Staff"',
        '"【フレイル】柄の先に鎖で石球をつないだ連接棍棒。"' : '"\[Flail\] A flail with a stone head attached to its \\nhandle with a chain."',
        '"柄の先に鎖で石球をつないだ連接棍棒。"' : '"A flail with a stone head attached to its \\nhandle with a chain."',
        '"name"\:"ストーンフレイル"' : '"name"\:"Stone Flail"',
        '"【フレイル】柄の先に鎖で銅球をつないだ連接棍棒。"' : '"\[Flail\] A flail with a bronze head attached to its \\nhandle with a chain."',
        '"柄の先に鎖で銅球をつないだ連接棍棒。"' : '"A flail with a bronze head attached to its \\nhandle with a chain."',
        '"name"\:"ブロンズフレイル"' : '"name"\:"Bronze Flail"',
        '"【フレイル】鋼鉄で強化した連接棍棒。"' : '"\[Flail\] A flail fortified with iron steel."',
        '"鋼鉄で強化した連接棍棒。"' : '"A flail fortified with iron steel."',
        '"name"\:"モーニングスター"' : '"name"\:"Morning Star"',
        '"【フレイル】ミスリルで強化した連接棍棒。"' : '"\[Flail\] A flail fortified with mithril."',
        '"ミスリルで強化した連接棍棒。"' : '"A flail fortified with mithril."',
        '"name"\:"ミスリルフレイル"' : '"name"\:"Mithril Flail"',
        '"【フレイル】ドラゴンのキバで強化した連接棍棒。"' : '"\[Flail\] A flail fortified with dragon\'s fangs."',
        '"ドラゴンのキバで強化した連接棍棒。"' : '"A flail fortified with dragon\'s fangs."',
        '"name"\:"ドラゴンフレイル"' : '"name"\:"Dragon Flail"',
        '"【斧】伐採に使う小型の斧。"' : '"\[Axe\] A small axe used for logging trees."',
        '"伐採に使う小型の斧。"' : '"A small axe used for logging trees."',
        '"name"\:"ハンドアクス"' : '"name"\:"Hand Axe"',
        '"【斧】戦闘用に作られた両刃の斧。"' : '"\[Axe\] A double-edged axe made for battle."',
        '"戦闘用に作られた両刃の斧。"' : '"A double-edged axe made for battle."',
        '"name"\:"バトルアクス"' : '"name"\:"Battle Axe"',
        '"【斧】三日月型の刃をもつ戦斧。"' : '"\[Axe\] A battle axe with a crescent-shaped blade."',
        '"三日月型の刃をもつ戦斧。"' : '"A battle axe with a crescent-shaped blade."',
        '"name"\:"バルディッシュ"' : '"name"\:"Bardiche"',
        '"【斧】ミスリルで作られた戦斧。"' : '"\[Axe\] A battle axe forged of mithril."',
        '"ミスリルで作られた戦斧。"' : '"A battle axe forged of mithril."',
        '"name"\:"ミスリルアスク"' : '"name"\:"Mithril Axe"',
        '"【斧】ドラゴンのキバで作られた戦斧。"' : '"\[Axe\] A battle axe forged of dragon\'s fangs."',
        '"ドラゴンのキバで作られた戦斧。"' : '"A battle axe forged of dragon\'s fangs."',
        '"name"\:"ドラゴンアスク"' : '"name"\:"Dragon Axe"',
        '"【槍】突きに特化させた短めの槍。"' : '"\[Spear\] A short spear specialized in thrusting. "',
        '"突きに特化させた短めの槍。"' : '"A short spear specialized in thrusting. "',
        '"name"\:"ショートスピア"' : '"name"\:"Short Spear"',
        '"【槍】柄を可能な限り長くした槍。"' : '"\[Spear\] A spear with the longest handle possible. "',
        '"柄を可能な限り長くした槍。"' : '"A spear with the longest handle possible. "',
        '"name"\:"ロングスピア"' : '"name"\:"Long Spear"',
        '"【槍】穂先に斧頭の取りつけられた槍。"' : '"\[Spear\] A spear with an axe-head at its tip."',
        '"穂先に斧頭の取りつけられた槍。"' : '"A spear with an axe-head at its tip."',
        '"name"\:"ハルバード"' : '"name"\:"Halberd"',
        '"【槍】ミスリルで作られた槍。"' : '"\[Spear\] A spear forged of mithril."',
        '"ミスリルで作られた槍。"' : '"A spear forged of mithril."',
        '"name"\:"ミスリルスピア"' : '"name"\:"Mithril Spear"',
        '"【槍】ドラゴンのキバで作られた槍。"' : '"\[Spear\] A spear forged of dragon\'s fangs."',
        '"ドラゴンのキバで作られた槍。"' : '"A spear forged of dragon\'s fangs."',
        '"name"\:"ドラゴンスピア"' : '"name"\:"Dragon Spear"',
        '"【グローブ】拳頭にトゲがついた格闘用のグローブ。"' : '"\[Glove\] A battle glove with spikes attached to its \\nknuckles. "',
        '"拳頭にトゲがついた格闘用のグローブ。"' : '"A battle glove with spikes attached to its \\nknuckles. "',
        '"name"\:"セスタス"' : '"name"\:"Cestus"',
        '"【爪】短い４本の爪が取りつけられた格闘武器。"' : '"\[Claw\] A combat weapon with 4 short claws attached."',
        '"短い４本の爪が取りつけられた格闘武器。"' : '"A combat weapon with 4 short claws attached."',
        '"name"\:"バグナウ"' : '"name"\:"Bagh Naka"',
        '"【爪】鋼鉄のかぎ爪が仕込まれた格闘武器。"' : '"\[Claw\] A combat weapon with iron talons attached."',
        '"鋼鉄のかぎ爪が仕込まれた格闘武器。"' : '"A combat weapon with iron talons attached."',
        '"name"\:"アイアンクロウ"' : '"name"\:"Iron Claw"',
        '"【爪】ミスリルのかぎ爪が仕込まれた格闘武器。"' : '"\[Claw\] A combat weapon with mithril talons attached."',
        '"ミスリルのかぎ爪が仕込まれた格闘武器。"' : '"A combat weapon with mithril talons attached."',
        '"name"\:"ミスリルクロウ"' : '"name"\:"Mithril Claw"',
        '"【爪】ドラゴンのかぎ爪が仕込まれた格闘武器。"' : '"\[Claw\] A combat weapon with dragon talons attached."',
        '"ドラゴンのかぎ爪が仕込まれた格闘武器。"' : '"A combat weapon with dragon talons attached."',
        '"name"\:"ドラゴンクロウ"' : '"name"\:"Dragon Claw"',
        '"【弓】狩猟用に作られた短めの弓。"' : '"\[Bow\] A short bow made for hunting."',
        '"狩猟用に作られた短めの弓。"' : '"A short bow made for hunting."',
        '"name"\:"ショートボウ"' : '"name"\:"Short Bow"',
        '"【弓】威力を高めた戦闘用の長弓。"' : '"\[Bow\] A long bow for battle with superior power."',
        '"威力を高めた戦闘用の長弓。"' : '"A long bow for battle with superior power."',
        '"name"\:"ロングボウ"' : '"name"\:"Long Bow"',
        '"【弓】強力なバネで矢を射出する石弓。"' : '"\[Bow\] A crossbow that shoots arrows with powerful \\nsprings."',
        '"強力なバネで矢を射出する石弓。"' : '"A crossbow that shoots arrows with powerful \\nsprings."',
        '"name"\:"クロスボウ"' : '"name"\:"Crossbow"',
        '"【弓】強力なバネでミスリルの矢を射出する石弓。"' : '"\[Bow\] A crossbow that shoots mithril arrows with \\npowerful springs."',
        '"強力なバネでミスリルの矢を射出する石弓。"' : '"A crossbow that shoots mithril arrows with \\npowerful springs."',
        '"name"\:"ミスリルボウ"' : '"name"\:"Mithril Bow"',
        '"【弓】ドラゴンのヒゲで作られた戦闘用の長弓。"' : '"\[Bow\] A long bow for battle made with dragon\'s \\nwhiskers."',
        '"ドラゴンのヒゲで作られた戦闘用の長弓。"' : '"A long bow for battle made with dragon\'s \\nwhiskers."',
        '"name"\:"ドラゴンボウ"' : '"name"\:"Dragon Bow"',
        '"【短剣】日常生活にも使えるナイフ。"' : '"\[Dagger\] A knife used for day-to-day tasks."',
        '"日常生活にも使えるナイフ。"' : '"A knife used for day-to-day tasks."',
        '"name"\:"ナイフ"' : '"name"\:"Knife"',
        '"【短剣】戦闘用の短刀。"' : '"\[Dagger\] A short blade used for battle. "',
        '"戦闘用の短刀。"' : '"A short blade used for battle. "',
        '"name"\:"ダガー"' : '"name"\:"Daggar"',
        '"【短剣】刀身が厚く丈夫な短刀。"' : '"\[Dagger\] A dagger with a thick, sturdy blade. "',
        '"刀身が厚く丈夫な短刀。"' : '"A dagger with a thick, sturdy blade. "',
        '"name"\:"マシェット"' : '"name"\:"Machete"',
        '"【短剣】ミスリルで作られた短刀。"' : '"\[Dagger\] A dagger forged of mithril."',
        '"ミスリルで作られた短刀。"' : '"A dagger forged of mithril."',
        '"name"\:"ミスリルダガー"' : '"name"\:"Mithril Daggar"',
        '"【短剣】ドラゴンのキバで作られた短刀。"' : '"\[Dagger\] A dagger forged of dragon\'s fangs"',
        '"ドラゴンのキバで作られた短刀。"' : '"A dagger forged of dragon\'s fangs"',
        '"name"\:"ドラゴンダガー"' : '"name"\:"Dragon Daggar"',
// non-original
        '"name"\:"レイピア"' : '"name"\:"Rapier"',
        '"name"\:"ブロードソード"' : '"name"\:"Broad sword"',
        '"name"\:"フランベルジュ"' : '"name"\:"Flamberge"',
        '"name"\:"クレイモア"' : '"name"\:"Claymore"',
        '"name"\:"エストック"' : '"name"\:"Estoc"',
        '"name"\:"アロンダイト"' : '"name"\:"Arondight"',
        '"name"\:"クラウソラス"' : '"name"\:"Cutlass"',
        '"name"\:"グラディウス"' : '"name"\:"Gladius"',
        '"name"\:"オブシダンソード"' : '"name"\:"Obsidian Sword"',
        '"name"\:"ブレイブソード"' : '"name"\:"Brave Sword"',
        '"name"\:"バトルアックス"' : '"name"\:"Battle Axe"',
        '"name"\:"樫の杖"' : '"name"\:"Wood Staff"',
        '"硬い樫の木で作られた杖。"' : '"A simple cane made from oak."',
//        '' : '',
    ///////////////////////////////////////////////////////
    '':''};











    //////////////////////////////////////////////////////////////////////////////
    // This is where the real code is
    // Don't edit below this
    //////////////////////////////////////////////////////////////////////////////

    var regexs = [], replacements = [],
        tagsWhitelist = ['INPUT', 'TEXTAREA'],
        rIsRegexp = /^\/(.+)\/([gim]+)?$/,
        word, text, texts, i, userRegexp;

    // prepareRegex by JoeSimmons
    // used to take a string and ready it for use in new RegExp()
    function prepareRegex(string) {
        return string.replace(/([\[\]\^\&\$\.\(\)\?\/\\\+\{\}\|])/g, '\\$1');
    }

    // function to decide whether a parent tag will have its text replaced or not
    function isTagOk(tag) {
        return tagsWhitelist.indexOf(tag) === -1;
    }

    delete words['']; // so the user can add each entry ending with a comma,
                      // I put an extra empty key/value pair in the object.
                      // so we need to remove it before continuing

    // convert the 'words' JSON object to an Array
    for (word in words) {
        if ( typeof word === 'string' && words.hasOwnProperty(word) ) {
            userRegexp = word.match(rIsRegexp);

            // add the search/needle/query
            if (userRegexp) {
                regexs.push(
                    new RegExp(userRegexp[1], 'g')
                );
            } else {
                regexs.push(
                    new RegExp(prepareRegex(word).replace(/\\?\*/g, function (fullMatch) {
                        return fullMatch === '\\*' ? '*' : '[^ ]*';
                    }), 'g')
                );
            }

            // add the replacement
            replacements.push( words[word] );
        }
    }

    // do the replacement
    texts = document.evaluate('//body//text()[ normalize-space(.) != "" ]', document, null, 6, null);
    for (i = 0; text = texts.snapshotItem(i); i += 1) {
        if ( isTagOk(text.parentNode.tagName) ) {
            regexs.forEach(function (value, index) {
                text.data = text.data.replace( value, replacements[index] );
            });
        }
    }

}());
